using MESService.Models;

namespace MESService.Model
{
    public partial class BaseResult : MESService.Model.BaseModel
    {
        public int? TB_PART_CNT { get; set; }
        public int? RAW_PART_CNT { get; set; }
        public List<SuperResultTranfer>? DGV_B03_01 { get; set; }
        public List<SuperResultTranfer>? DGV_B07_31 { get; set; }
        public List<SuperResultTranfer>? DGV_B07_32 { get; set; }
        public List<SuperResultTranfer>? DGV_C09_01 { get; set; }
        public List<SuperResultTranfer>? DGV_B08_01 { get; set; }
        public List<SuperResultTranfer>? DGV_B08_02 { get; set; }
        public List<SuperResultTranfer>? DGV_B08_03 { get; set; }
        public List<SuperResultTranfer>? DGV_A01_01 { get; set; }
        public List<SuperResultTranfer>? DGV_A01_01_1 { get; set; }
        public List<SuperResultTranfer>? DGV_A01_CB1 { get; set; }
        public List<SuperResultTranfer>? cb_Stage1 { get; set; }
        public List<SuperResultTranfer>? T2_S1 { get; set; }
        public List<SuperResultTranfer>? T2_DGV1 { get; set; }
        public List<SuperResultTranfer>? CB_FCTRY1 { get; set; }
        public List<SuperResultTranfer>? T3_S1 { get; set; }
        public List<SuperResultTranfer>? DGV_G02_01 { get; set; }
        public List<SuperResultTranfer>? DGV_G02_CB { get; set; }
        public List<SuperResultTranfer>? DGV_G04_CB1 { get; set; }
        public List<SuperResultTranfer>? DGV_V01_CB1 { get; set; }
        public List<SuperResultTranfer>? DGV_01 { get; set; }
        public List<tspart>? DGV_B01_01 { get; set; }
        public List<NGList>? NGLists { get; set; }
        public List<FAWorkOrderHistory> FAWorkOrderHistoryList { get; set; }
        public List<FAWorkOrder>? FAWorkOrderList { get; set; }
        public List<TaskTimeFA> TaskTimeFAList { get; set; }
        public List<SuperResultTranfer>? ComboBox1 { get; set; }
        public List<SuperResultTranfer>? ComboBox2 { get; set; }
        public List<SuperResultTranfer>? ComboBox3 { get; set; }
        public List<SuperResultTranfer>? ComboBoxData { get; set; }
        public List<SuperResultTranfer>? ComboBox4 { get; set; }
        public List<LineList>? LineList { get; set; }
        public List<LineAssignment> LineAssignments { get; set; }
        public List<FAProduction> FAProductionList { get; set; }
        public List<AttendanceSession> AttendanceSessionList { get; set; }
        public List<P04>? ListP04 { get; set; }
        public List<ShiftTime>? ShiftTimes { get; set; }
        public List<TaskTimeStandard> ListTaskTimeStandard { get; set; }
        public List<TaskTimeFA> ListTaskTimeFA { get; set; }
        public int? ErrorNumber { get; set; }
        public int? SaveSuccessNumber { get; set; }
        public int? SaveNotSuccessNumber { get; set; }
        public bool? DGV_result3 { get; set; }
        public List<SuperResultTranfer>? DGV_WMP_PLIST { get; set; }
        public List<SuperResultTranfer>? DGV_B09_91 { get; set; }
        public List<SuperResultTranfer>? DGV_B04_BCTXT { get; set; }
        public List<tmbrcdTranfer>? ListtmbrcdTranfer01 { get; set; }
        public List<tmbrcdTranfer>? ListtmbrcdTranfer02 { get; set; }
        public List<SuperResultTranfer>? DGV_LIST { get; set; }
        public List<SuperResultTranfer>? T_DGV_02 { get; set; }
        public List<SuperResultTranfer>? CALL_STOCK { get; set; }
        public List<SuperResultTranfer>? T_DGV_01 { get; set; }
        public List<SuperResultTranfer>? DataGridView { get; set; }
        public List<SuperResultTranfer>? DataGridView0 { get; set; }
        public List<SuperResultTranfer>? DataGridView1 { get; set; }
        public List<SuperResultTranfer>? DataGridView2 { get; set; }
        public List<SuperResultTranfer>? DataGridView3 { get; set; }
        public List<SuperResultTranfer>? DataGridView4 { get; set; }
        public List<SuperResultTranfer>? DataGridView5 { get; set; }
        public List<SuperResultTranfer>? DataGridView6 { get; set; }
        public List<SuperResultTranfer>? DataGridView8 { get; set; }
        public List<SuperResultTranfer>? DataGridView7 { get; set; }
        public List<SuperResultTranfer>? DataGridView9 { get; set; }
        public List<SuperResultTranfer>? DGV_B04_03 { get; set; }
        public List<SuperResultTranfer>? DGV_B04_02 { get; set; }
        public List<SuperResultTranfer>? IN_LIST_DGV { get; set; }
        public List<SuperResultTranfer>? DGV_B08_09_1 { get; set; }
        public List<SuperResultTranfer>? OUT_LIST_DGV { get; set; }
        public List<V01_DMPS_COST>? V01_DMPS_COST_DataGridView3 { get; set; }
        public List<SuperResultTranfer>? DGV_A07_01 { get; set; }
        public List<string>? ListSearchString { get; set; }
        public List<B01>? ListB01 { get; set; }
        public List<B02>? ListB02 { get; set; }
        public List<NGDataTranfer>? NGDataList { get; set; }
        public List<D01Model>? List_D01 { get; set; }
        public List<B02>? BarcodeDGV { get; set; }
        public string? Code { get; set; }
        public string? Error { get; set; }
        public string? Message { get; set; }
        public List<Dictionary<string, object>>? DataGridView5Raw { get; set; }
        public List<dynamic>? G01Overview { get; set; }
        public List<dynamic>? G01RawMaterial { get; set; }
        public List<dynamic>? G01FinishedGood { get; set; }
        public List<dynamic>? G01HookRack { get; set; }
        public List<dynamic> MachineStatusList { get; set; } = new List<dynamic>();
        public dynamic MaintenanceDetail { get; set; }
        public int? G01RawMaterialGood { get; set; }
        public int? G01RawMaterialBad { get; set; }
        public int? G01FinishedGoodGood { get; set; }
        public int? G01FinishedGoodBad { get; set; }
        public int? G01HookRackGood { get; set; }
        public int? G01HookRackBad { get; set; }
        public object? Data { get; set; }
        public List<string>? Barcodes { get; set; }

        public string? AudioCue { get; set; }
        public bool ClearInput { get; set; }
        public bool Success { get; set; }
        public string? PackingLotCode { get; set; }
        public string? AUTO_DT { get; set; }
        public int? WW1 { get; set; }
        public int? WW2 { get; set; }
        public int? WW3 { get; set; }
        public int? WW4 { get; set; }
        public int? WW5 { get; set; }
        public int? WW6 { get; set; }
        public double? QTY_SUM { get; set; }
        public double? CHK_PM { get; set; }
        public string? QRCodeData { get; set; }
        public string? QRCodeText { get; set; }
        public string? BoxNumber { get; set; }
        public List<FAPersonnel> FAPersonnelList { get; set; }
        public List<ROTestLog> ROTestLogList { get; set; }
        public List<OQC_NG> OQC_NGList { get; set; }
        public List<ToolShop>? ToolShopList { get; set; }
        public List<SuperResultTranfer>? DGV_Z04_CB { get; set; }
        public List<SuperResultTranfer>? DGV_Z04_CB_1 { get; set; }
        public List<SuperResultTranfer>? DGV_Z04_02 { get; set; }
        public List<SuperResultTranfer>? DGV_Z04_03 { get; set; }
        public string? Label15 { get; set; }
        public string? Label11 { get; set; }
        public string? Label38 { get; set; }
        public string? TextBox4 { get; set; }
        public string? TextBox6 { get; set; }
        public string? TextBox7 { get; set; }
        public string? TextBox8 { get; set; }
        public string? TextBox9 { get; set; }
        public string? TextBox10 { get; set; }
        public string? TextBox11 { get; set; }
        public string? TextBox12 { get; set; }
        public string? TextBox13 { get; set; }
        public string? TextBox14 { get; set; }
        public string? TextBox15 { get; set; }
        public string? TextBox16 { get; set; }
        public string? TextBox17 { get; set; }
        public string? TextBox18 { get; set; }
        public string? TextBox19 { get; set; }
        public string? TextBox20 { get; set; }
        public string? TextBox21 { get; set; }
        public string? TextBox22 { get; set; }
        public string? TextBox23 { get; set; }
        public string? TextBox24 { get; set; }
        public string? TextBox25 { get; set; }
        public string? TextBox26 { get; set; }
        public string? TextBox27 { get; set; }
        public string? TextBox29 { get; set; }
        public string? DSCN { get; set; }
        public string? LEAD_INDEX { get; set; }
        public string? LEAD_SCN { get; set; }
        public string? DATEString { get; set; }
        public EmployeeFA EmployeeFA { get; set; }
        public List<EmployeeFA> EmployeeFAList { get; set; }
        public List<Attendance> AttendanceList { get; set; }
        public List<string> MachineList { get; set; }
        public string? SUM_QTY { get; set; }
        public string? OUT_QTY { get; set; }
        public Dictionary<string, string>? LeadDetail { get; set; }
        public string? Label2 { get; set; }
        public string? Label3 { get; set; }
        public int? LEAD_CONT_OUT { get; set; }
        public string? LEAD_NM { get; set; }
        public string? BARCODE_NM { get; set; }
        public string? TRACK_IDX { get; set; }
        public string? RACKOUT_DTM { get; set; }
        public string? Label4 { get; set; }
        public string? Label5 { get; set; }
        public string? Label12 { get; set; }
        public string? Label37 { get; set; }
        public string? TextBox1 { get; set; }
        public List<SuperResultTranfer>? CB_01 { get; set; }
        public List<SuperResultTranfer>? USER_TIME { get; set; }
        public List<SuperResultTranfer>? USER_TIME1 { get; set; }
        public List<SuperResultTranfer>? DGV_C02_ML { get; set; }
        public List<SuperResultTranfer>? DGV_WT { get; set; }
        public List<SuperResultTranfer>? DGV_D11_NO { get; set; }
        public List<SuperResultTranfer>? DGV_OUT { get; set; }
        public List<SuperResultTranfer>? COUNT_DGV { get; set; }
        public List<SuperResultTranfer>? COUNT_DGV_CHK { get; set; }
        public List<SuperResultTranfer>? DGV_D04_ALOC { get; set; }
        public bool? QTY_CHK { get; set; }
        public string? PO_LOC { get; set; }
        public bool? LOC_CHK { get; set; }
        public int? ckAA { get; set; }
        public int? ckBB { get; set; }
        public int? TOT_QTY { get; set; }
        public int? qtyAA { get; set; }
        public string? SP_CHK { get; set; }
        public bool? S_CHKPART { get; set; }
        public bool? CHK_PART { get; set; }
        public List<SuperResultTranfer>? DataGridView11 { get; set; }
        public List<ScrapListTranfer>? ScrapListView { get; set; }
        public List<SuperResultTranfer>? DGV_D04_07 { get; set; }
        public List<SuperResultTranfer>? DataGridView10 { get; set; }
        public List<SuperResultTranfer>? Search { get; set; }
        public List<SuperResultTranfer>? DGV_D04_CB1 { get; set; }
        public List<SuperResultTranfer>? DGV_PNOCHK_01 { get; set; }
        public string? PART_IDX { get; set; }
        public List<SuperResultTranfer>? DGV_D04_PO01 { get; set; }
        public List<SuperResultTranfer>? Search1 { get; set; }
        public List<SuperResultTranfer>? DGV_C09_ST_00 { get; set; }
        public List<SuperResultTranfer>? DGV_C09_ST_BOM { get; set; }
        public List<SuperResultTranfer>? DGV_C09_13 { get; set; }
        public List<SuperResultTranfer>? DataGridView12 { get; set; }
        public int? ORDER_IDX { get; set; }
        public List<SuperResultTranfer>? SW_BOM { get; set; }
        public List<SuperResultTranfer>? spcListDetail { get; set; }
        public string? TimeS { get; set; }
        public int TotalCount { get; set; }
        public List<AttendanceRecords> AttendanceRecordsList { get; set; }
        public List<SuperResultTranfer> ProductionTrend { get; set; }
        public List<SuperResultTranfer> DowntimeAnalysis { get; set; }

        public string? DeviceCode { get; set; }
        public string? DeviceGroup { get; set; }
        public int? QuantityRequired { get; set; }
        public int? SafetyStock { get; set; }
        public List<Dictionary<string, object>>? ReportData { get; set; }
        public List<CategoryDepartment> ListCategoryDepartment { get; set; }
        public List<Material> ListMaterial { get; set; }
        public List<WarehouseRequestDetail> ListWarehouseRequestDetail { get; set; }
        public tfg_inventory tfg_inventory { get; set; }
        public List<tfg_inventory> tfg_inventoryList { get; set; }
        public List<tfg_packing_detail> tfg_packing_detailList { get; set; }
        public List<tfg_history> tfg_historyList { get; set; }
        public List<MaintenanceHistory> MaintenanceHistoryList { get; set; }
        public List<PartSpare>? PartSpareList { get; set; }
        public List<PartSpareScanOut>? PartSpareScanOutList { get; set; }
        public List<PartSpareScanIn>? PartSpareScanInList { get; set; }
        public List<WarehouseOutput> ListWarehouseOutput { get; set; }
        public List<WarehouseOutputDetail> ListWarehouseOutputDetail { get; set; }
        public List<WarehouseOutputDetailBarcode> ListWarehouseOutputDetailBarcode { get; set; }
        public List<WarehouseInput> ListWarehouseInput { get; set; }
        public List<WarehouseInputDetail> ListWarehouseInputDetail { get; set; }
        public List<WarehouseInputDetailBarcode> ListWarehouseInputDetailBarcode { get; set; }
        public List<WarehouseRequest> ListWarehouseRequest { get; set; }
        public List<WarehouseRequestDetail> ListWarehouseRequestDetail1 { get; set; }
        public List<HistoryDataTranfer> HistoryDataList { get; set; }
        public Trolley Trolley { get; set; }
        public List<Trolley> TrolleyList { get; set; }
        public string TrolleyCode { get; set; }
        public string Location { get; set; }
        public List<TrolleyBarcodeItem> TrolleyBarcodes { get; set; }
        public List<TrolleySummaryItem> TrolleySummary { get; set; }
        public int SuccessCount { get; set; }
        public List<IQCNGCustomer2>? IQCNGCustomer2List { get; set; }

        public int Progress { get; set; }
        public DateTime? LastUpdated { get; set; }
        public string DownloadUrl { get; set; } // Dùng string thay vì object để rõ ràng hơn
        public string JobId { get; set; } // Thêm JobId nếu chưa có
                                          // Thêm các trường mới cho tiến độ chi tiết
        public int CurrentRow { get; set; }
        public int TotalRows { get; set; }
        public string CurrentAction { get; set; }
        public bool RequireChangePassword { get; internal set; }

        public BaseResult()
        {
            Success = false;
        }
    }
}

