namespace MESService.Model
{
    public class BaseModel
    {
        public SuperResultTranfer? SuperResultTranfer { get; set; }
        public List<SuperResultTranfer>? ListSuperResultTranfer { get; set; }
        public aatable? aatable { get; set; }
        public aatableTranfer? aatableTranfer { get; set; }
        public List<aatable>? Listaatable { get; set; }
        public List<aatableTranfer>? ListaatableTranfer { get; set; }
        public apqp_cdgr? apqp_cdgr { get; set; }
        public apqp_cdgrTranfer? apqp_cdgrTranfer { get; set; }
        public List<apqp_cdgr>? Listapqp_cdgr { get; set; }
        public List<apqp_cdgrTranfer>? Listapqp_cdgrTranfer { get; set; }
        public apqp_code? apqp_code { get; set; }
        public apqp_codeTranfer? apqp_codeTranfer { get; set; }
        public List<apqp_code>? Listapqp_code { get; set; }
        public List<apqp_codeTranfer>? Listapqp_codeTranfer { get; set; }
        public apqp_dlylst? apqp_dlylst { get; set; }
        public apqp_dlylstTranfer? apqp_dlylstTranfer { get; set; }
        public List<apqp_dlylst>? Listapqp_dlylst { get; set; }
        public List<apqp_dlylstTranfer>? Listapqp_dlylstTranfer { get; set; }
        public apqp_filelst? apqp_filelst { get; set; }
        public apqp_filelstTranfer? apqp_filelstTranfer { get; set; }
        public List<apqp_filelst>? Listapqp_filelst { get; set; }
        public List<apqp_filelstTranfer>? Listapqp_filelstTranfer { get; set; }
        public apqp_mstlst? apqp_mstlst { get; set; }
        public apqp_mstlstTranfer? apqp_mstlstTranfer { get; set; }
        public List<apqp_mstlst>? Listapqp_mstlst { get; set; }
        public List<apqp_mstlstTranfer>? Listapqp_mstlstTranfer { get; set; }
        public kr_inspctn_st? kr_inspctn_st { get; set; }
        public kr_inspctn_stTranfer? kr_inspctn_stTranfer { get; set; }
        public List<kr_inspctn_st>? Listkr_inspctn_st { get; set; }
        public List<kr_inspctn_stTranfer>? Listkr_inspctn_stTranfer { get; set; }
        public kr_inspctn_test? kr_inspctn_test { get; set; }
        public kr_inspctn_testTranfer? kr_inspctn_testTranfer { get; set; }
        public List<kr_inspctn_test>? Listkr_inspctn_test { get; set; }
        public List<kr_inspctn_testTranfer>? Listkr_inspctn_testTranfer { get; set; }
        public kr_tdd_poplan? kr_tdd_poplan { get; set; }
        public kr_tdd_poplanTranfer? kr_tdd_poplanTranfer { get; set; }
        public List<kr_tdd_poplan>? Listkr_tdd_poplan { get; set; }
        public List<kr_tdd_poplanTranfer>? Listkr_tdd_poplanTranfer { get; set; }
        public kr_tdpdmtim? kr_tdpdmtim { get; set; }
        public kr_tdpdmtimTranfer? kr_tdpdmtimTranfer { get; set; }
        public List<kr_tdpdmtim>? Listkr_tdpdmtim { get; set; }
        public List<kr_tdpdmtimTranfer>? Listkr_tdpdmtimTranfer { get; set; }
        public kr_tdpdmtim_tmp? kr_tdpdmtim_tmp { get; set; }
        public kr_tdpdmtim_tmpTranfer? kr_tdpdmtim_tmpTranfer { get; set; }
        public List<kr_tdpdmtim_tmp>? Listkr_tdpdmtim_tmp { get; set; }
        public List<kr_tdpdmtim_tmpTranfer>? Listkr_tdpdmtim_tmpTranfer { get; set; }
        public kr_tdpdmtim_tmp_out? kr_tdpdmtim_tmp_out { get; set; }
        public kr_tdpdmtim_tmp_outTranfer? kr_tdpdmtim_tmp_outTranfer { get; set; }
        public List<kr_tdpdmtim_tmp_out>? Listkr_tdpdmtim_tmp_out { get; set; }
        public List<kr_tdpdmtim_tmp_outTranfer>? Listkr_tdpdmtim_tmp_outTranfer { get; set; }
        public kr_tdpdotpl? kr_tdpdotpl { get; set; }
        public kr_tdpdotplTranfer? kr_tdpdotplTranfer { get; set; }
        public List<kr_tdpdotpl>? Listkr_tdpdotpl { get; set; }
        public List<kr_tdpdotplTranfer>? Listkr_tdpdotplTranfer { get; set; }
        public kr_tdpdotpl_inpo? kr_tdpdotpl_inpo { get; set; }
        public kr_tdpdotpl_inpoTranfer? kr_tdpdotpl_inpoTranfer { get; set; }
        public List<kr_tdpdotpl_inpo>? Listkr_tdpdotpl_inpo { get; set; }
        public List<kr_tdpdotpl_inpoTranfer>? Listkr_tdpdotpl_inpoTranfer { get; set; }
        public kr_tiivtr? kr_tiivtr { get; set; }
        public kr_tiivtrTranfer? kr_tiivtrTranfer { get; set; }
        public List<kr_tiivtr>? Listkr_tiivtr { get; set; }
        public List<kr_tiivtrTranfer>? Listkr_tiivtrTranfer { get; set; }
        public pd_asset_mm? pd_asset_mm { get; set; }
        public pd_asset_mmTranfer? pd_asset_mmTranfer { get; set; }
        public List<pd_asset_mm>? Listpd_asset_mm { get; set; }
        public List<pd_asset_mmTranfer>? Listpd_asset_mmTranfer { get; set; }
        public pd_cmpny_costfile? pd_cmpny_costfile { get; set; }
        public pd_cmpny_costfileTranfer? pd_cmpny_costfileTranfer { get; set; }
        public List<pd_cmpny_costfile>? Listpd_cmpny_costfile { get; set; }
        public List<pd_cmpny_costfileTranfer>? Listpd_cmpny_costfileTranfer { get; set; }
        public pd_cmpny_part? pd_cmpny_part { get; set; }
        public pd_cmpny_partTranfer? pd_cmpny_partTranfer { get; set; }
        public List<pd_cmpny_part>? Listpd_cmpny_part { get; set; }
        public List<pd_cmpny_partTranfer>? Listpd_cmpny_partTranfer { get; set; }
        public pd_inout_part? pd_inout_part { get; set; }
        public pd_inout_partTranfer? pd_inout_partTranfer { get; set; }
        public List<pd_inout_part>? Listpd_inout_part { get; set; }
        public List<pd_inout_partTranfer>? Listpd_inout_partTranfer { get; set; }
        public pd_mc_orderlist? pd_mc_orderlist { get; set; }
        public pd_mc_orderlistTranfer? pd_mc_orderlistTranfer { get; set; }
        public List<pd_mc_orderlist>? Listpd_mc_orderlist { get; set; }
        public List<pd_mc_orderlistTranfer>? Listpd_mc_orderlistTranfer { get; set; }
        public pd_part_cost? pd_part_cost { get; set; }
        public pd_part_costTranfer? pd_part_costTranfer { get; set; }
        public List<pd_part_cost>? Listpd_part_cost { get; set; }
        public List<pd_part_costTranfer>? Listpd_part_costTranfer { get; set; }
        public pd_tiivtr? pd_tiivtr { get; set; }
        public pd_tiivtrTranfer? pd_tiivtrTranfer { get; set; }
        public List<pd_tiivtr>? Listpd_tiivtr { get; set; }
        public List<pd_tiivtrTranfer>? Listpd_tiivtrTranfer { get; set; }
        public pdcdgr? pdcdgr { get; set; }
        public pdcdgrTranfer? pdcdgrTranfer { get; set; }
        public List<pdcdgr>? Listpdcdgr { get; set; }
        public List<pdcdgrTranfer>? ListpdcdgrTranfer { get; set; }
        public pdcdnm? pdcdnm { get; set; }
        public pdcdnmTranfer? pdcdnmTranfer { get; set; }
        public List<pdcdnm>? Listpdcdnm { get; set; }
        public List<pdcdnmTranfer>? ListpdcdnmTranfer { get; set; }
        public pdcmpny? pdcmpny { get; set; }
        public pdcmpnyTranfer? pdcmpnyTranfer { get; set; }
        public List<pdcmpny>? Listpdcmpny { get; set; }
        public List<pdcmpnyTranfer>? ListpdcmpnyTranfer { get; set; }
        public pdpart? pdpart { get; set; }
        public pdpartTranfer? pdpartTranfer { get; set; }
        public List<pdpart>? Listpdpart { get; set; }
        public List<pdpartTranfer>? ListpdpartTranfer { get; set; }
        public pdpart_addlist? pdpart_addlist { get; set; }
        public pdpart_addlistTranfer? pdpart_addlistTranfer { get; set; }
        public List<pdpart_addlist>? Listpdpart_addlist { get; set; }
        public List<pdpart_addlistTranfer>? Listpdpart_addlistTranfer { get; set; }
        public pdpusch? pdpusch { get; set; }
        public pdpuschTranfer? pdpuschTranfer { get; set; }
        public List<pdpusch>? Listpdpusch { get; set; }
        public List<pdpuschTranfer>? ListpdpuschTranfer { get; set; }
        public tdd_ct_st? tdd_ct_st { get; set; }
        public tdd_ct_stTranfer? tdd_ct_stTranfer { get; set; }
        public List<tdd_ct_st>? Listtdd_ct_st { get; set; }
        public List<tdd_ct_stTranfer>? Listtdd_ct_stTranfer { get; set; }
        public tdd_poplan? tdd_poplan { get; set; }
        public tdd_poplanTranfer? tdd_poplanTranfer { get; set; }
        public List<tdd_poplan>? Listtdd_poplan { get; set; }
        public List<tdd_poplanTranfer>? Listtdd_poplanTranfer { get; set; }
        public tdd_poplan_djg? tdd_poplan_djg { get; set; }
        public tdd_poplan_djgTranfer? tdd_poplan_djgTranfer { get; set; }
        public List<tdd_poplan_djg>? Listtdd_poplan_djg { get; set; }
        public List<tdd_poplan_djgTranfer>? Listtdd_poplan_djgTranfer { get; set; }
        public tdpdmtim? tdpdmtim { get; set; }
        public tdpdmtimTranfer? tdpdmtimTranfer { get; set; }
        public List<tdpdmtim>? Listtdpdmtim { get; set; }
        public List<tdpdmtimTranfer>? ListtdpdmtimTranfer { get; set; }
        public tdpdmtim_autobc_list? tdpdmtim_autobc_list { get; set; }
        public tdpdmtim_autobc_listTranfer? tdpdmtim_autobc_listTranfer { get; set; }
        public List<tdpdmtim_autobc_list>? Listtdpdmtim_autobc_list { get; set; }
        public List<tdpdmtim_autobc_listTranfer>? Listtdpdmtim_autobc_listTranfer { get; set; }
        public tdpdmtim_del? tdpdmtim_del { get; set; }
        public tdpdmtim_delTranfer? tdpdmtim_delTranfer { get; set; }
        public List<tdpdmtim_del>? Listtdpdmtim_del { get; set; }
        public List<tdpdmtim_delTranfer>? Listtdpdmtim_delTranfer { get; set; }
        public tdpdmtim_hist? tdpdmtim_hist { get; set; }
        public tdpdmtim_histTranfer? tdpdmtim_histTranfer { get; set; }
        public List<tdpdmtim_hist>? Listtdpdmtim_hist { get; set; }
        public List<tdpdmtim_histTranfer>? Listtdpdmtim_histTranfer { get; set; }
        public tdpdmtim_loc? tdpdmtim_loc { get; set; }
        public tdpdmtim_locTranfer? tdpdmtim_locTranfer { get; set; }
        public List<tdpdmtim_loc>? Listtdpdmtim_loc { get; set; }
        public List<tdpdmtim_locTranfer>? Listtdpdmtim_locTranfer { get; set; }
        public tdpdmtim_rework? tdpdmtim_rework { get; set; }
        public tdpdmtim_reworkTranfer? tdpdmtim_reworkTranfer { get; set; }
        public List<tdpdmtim_rework>? Listtdpdmtim_rework { get; set; }
        public List<tdpdmtim_reworkTranfer>? Listtdpdmtim_reworkTranfer { get; set; }
        public tdpdmtim_tmp? tdpdmtim_tmp { get; set; }
        public tdpdmtim_tmpTranfer? tdpdmtim_tmpTranfer { get; set; }
        public List<tdpdmtim_tmp>? Listtdpdmtim_tmp { get; set; }
        public List<tdpdmtim_tmpTranfer>? Listtdpdmtim_tmpTranfer { get; set; }
        public tdpdmtin_serial? tdpdmtin_serial { get; set; }
        public tdpdmtin_serialTranfer? tdpdmtin_serialTranfer { get; set; }
        public List<tdpdmtin_serial>? Listtdpdmtin_serial { get; set; }
        public List<tdpdmtin_serialTranfer>? Listtdpdmtin_serialTranfer { get; set; }
        public tdpdotpl? tdpdotpl { get; set; }
        public tdpdotplTranfer? tdpdotplTranfer { get; set; }
        public List<tdpdotpl>? Listtdpdotpl { get; set; }
        public List<tdpdotplTranfer>? ListtdpdotplTranfer { get; set; }
        public tdpdotpl_aloc? tdpdotpl_aloc { get; set; }
        public tdpdotpl_alocTranfer? tdpdotpl_alocTranfer { get; set; }
        public List<tdpdotpl_aloc>? Listtdpdotpl_aloc { get; set; }
        public List<tdpdotpl_alocTranfer>? Listtdpdotpl_alocTranfer { get; set; }
        public tdpdotpl_etc? tdpdotpl_etc { get; set; }
        public tdpdotpl_etcTranfer? tdpdotpl_etcTranfer { get; set; }
        public List<tdpdotpl_etc>? Listtdpdotpl_etc { get; set; }
        public List<tdpdotpl_etcTranfer>? Listtdpdotpl_etcTranfer { get; set; }
        public tdpdotpl_label? tdpdotpl_label { get; set; }
        public tdpdotpl_labelTranfer? tdpdotpl_labelTranfer { get; set; }
        public List<tdpdotpl_label>? Listtdpdotpl_label { get; set; }
        public List<tdpdotpl_labelTranfer>? Listtdpdotpl_labelTranfer { get; set; }
        public tdpdotpl_tmp? tdpdotpl_tmp { get; set; }
        public tdpdotpl_tmpTranfer? tdpdotpl_tmpTranfer { get; set; }
        public List<tdpdotpl_tmp>? Listtdpdotpl_tmp { get; set; }
        public List<tdpdotpl_tmpTranfer>? Listtdpdotpl_tmpTranfer { get; set; }
        public tdpdotplmu? tdpdotplmu { get; set; }
        public tdpdotplmuTranfer? tdpdotplmuTranfer { get; set; }
        public List<tdpdotplmu>? Listtdpdotplmu { get; set; }
        public List<tdpdotplmuTranfer>? ListtdpdotplmuTranfer { get; set; }
        public tfg_monitor? tfg_monitor { get; set; }
        public tfg_monitorTranfer? tfg_monitorTranfer { get; set; }
        public List<tfg_monitor>? Listtfg_monitor { get; set; }
        public List<tfg_monitorTranfer>? Listtfg_monitorTranfer { get; set; }
        public tiivaj? tiivaj { get; set; }
        public tiivajTranfer? tiivajTranfer { get; set; }
        public List<tiivaj>? Listtiivaj { get; set; }
        public List<tiivajTranfer>? ListtiivajTranfer { get; set; }
        public tiivaj_history? tiivaj_history { get; set; }
        public tiivaj_historyTranfer? tiivaj_historyTranfer { get; set; }
        public List<tiivaj_history>? Listtiivaj_history { get; set; }
        public List<tiivaj_historyTranfer>? Listtiivaj_historyTranfer { get; set; }
        public tiivaj_lead? tiivaj_lead { get; set; }
        public tiivaj_leadTranfer? tiivaj_leadTranfer { get; set; }
        public List<tiivaj_lead>? Listtiivaj_lead { get; set; }
        public List<tiivaj_leadTranfer>? Listtiivaj_leadTranfer { get; set; }
        public tiivtr? tiivtr { get; set; }
        public tiivtrTranfer? tiivtrTranfer { get; set; }
        public List<tiivtr>? Listtiivtr { get; set; }
        public List<tiivtrTranfer>? ListtiivtrTranfer { get; set; }
        public tiivtr_excel? tiivtr_excel { get; set; }
        public tiivtr_excelTranfer? tiivtr_excelTranfer { get; set; }
        public List<tiivtr_excel>? Listtiivtr_excel { get; set; }
        public List<tiivtr_excelTranfer>? Listtiivtr_excelTranfer { get; set; }
        public tiivtr_history? tiivtr_history { get; set; }
        public tiivtr_historyTranfer? tiivtr_historyTranfer { get; set; }
        public List<tiivtr_history>? Listtiivtr_history { get; set; }
        public List<tiivtr_historyTranfer>? Listtiivtr_historyTranfer { get; set; }
        public tiivtr_lead? tiivtr_lead { get; set; }
        public tiivtr_leadTranfer? tiivtr_leadTranfer { get; set; }
        public List<tiivtr_lead>? Listtiivtr_lead { get; set; }
        public List<tiivtr_leadTranfer>? Listtiivtr_leadTranfer { get; set; }
        public tiivtr_lead_fg? tiivtr_lead_fg { get; set; }
        public tiivtr_lead_fgTranfer? tiivtr_lead_fgTranfer { get; set; }
        public List<tiivtr_lead_fg>? Listtiivtr_lead_fg { get; set; }
        public List<tiivtr_lead_fgTranfer>? Listtiivtr_lead_fgTranfer { get; set; }
        public tiivtr_lead_history? tiivtr_lead_history { get; set; }
        public tiivtr_lead_historyTranfer? tiivtr_lead_historyTranfer { get; set; }
        public List<tiivtr_lead_history>? Listtiivtr_lead_history { get; set; }
        public List<tiivtr_lead_historyTranfer>? Listtiivtr_lead_historyTranfer { get; set; }
        public tmbrcd? tmbrcd { get; set; }
        public tmbrcdTranfer? tmbrcdTranfer { get; set; }
        public List<tmbrcd>? Listtmbrcd { get; set; }
        public List<tmbrcdTranfer>? ListtmbrcdTranfer { get; set; }
        public tmbrcd_his? tmbrcd_his { get; set; }
        public tmbrcd_hisTranfer? tmbrcd_hisTranfer { get; set; }
        public List<tmbrcd_his>? Listtmbrcd_his { get; set; }
        public List<tmbrcd_hisTranfer>? Listtmbrcd_hisTranfer { get; set; }
        public tmbrcd_longterm? tmbrcd_longterm { get; set; }
        public tmbrcd_longtermTranfer? tmbrcd_longtermTranfer { get; set; }
        public List<tmbrcd_longterm>? Listtmbrcd_longterm { get; set; }
        public List<tmbrcd_longtermTranfer>? Listtmbrcd_longtermTranfer { get; set; }
        public tmmtin? tmmtin { get; set; }
        public tmmtinTranfer? tmmtinTranfer { get; set; }
        public List<tmmtin>? Listtmmtin { get; set; }
        public List<tmmtinTranfer>? ListtmmtinTranfer { get; set; }
        public tmmtin_dmm? tmmtin_dmm { get; set; }
        public tmmtin_dmmTranfer? tmmtin_dmmTranfer { get; set; }
        public List<tmmtin_dmm>? Listtmmtin_dmm { get; set; }
        public List<tmmtin_dmmTranfer>? Listtmmtin_dmmTranfer { get; set; }
        public tmmtin_dmm_app? tmmtin_dmm_app { get; set; }
        public tmmtin_dmm_appTranfer? tmmtin_dmm_appTranfer { get; set; }
        public List<tmmtin_dmm_app>? Listtmmtin_dmm_app { get; set; }
        public List<tmmtin_dmm_appTranfer>? Listtmmtin_dmm_appTranfer { get; set; }
        public tmmtin_dmm_cut? tmmtin_dmm_cut { get; set; }
        public tmmtin_dmm_cutTranfer? tmmtin_dmm_cutTranfer { get; set; }
        public List<tmmtin_dmm_cut>? Listtmmtin_dmm_cut { get; set; }
        public List<tmmtin_dmm_cutTranfer>? Listtmmtin_dmm_cutTranfer { get; set; }
        public tmmtin_dmm_lead? tmmtin_dmm_lead { get; set; }
        public tmmtin_dmm_leadTranfer? tmmtin_dmm_leadTranfer { get; set; }
        public List<tmmtin_dmm_lead>? Listtmmtin_dmm_lead { get; set; }
        public List<tmmtin_dmm_leadTranfer>? Listtmmtin_dmm_leadTranfer { get; set; }
        public torder_barcode? torder_barcode { get; set; }
        public torder_barcodeTranfer? torder_barcodeTranfer { get; set; }
        public List<torder_barcode>? Listtorder_barcode { get; set; }
        public List<torder_barcodeTranfer>? Listtorder_barcodeTranfer { get; set; }
        public torder_barcode_lp? torder_barcode_lp { get; set; }
        public torder_barcode_lpTranfer? torder_barcode_lpTranfer { get; set; }
        public List<torder_barcode_lp>? Listtorder_barcode_lp { get; set; }
        public List<torder_barcode_lpTranfer>? Listtorder_barcode_lpTranfer { get; set; }
        public torder_barcode_sp? torder_barcode_sp { get; set; }
        public torder_barcode_spTranfer? torder_barcode_spTranfer { get; set; }
        public List<torder_barcode_sp>? Listtorder_barcode_sp { get; set; }
        public List<torder_barcode_spTranfer>? Listtorder_barcode_spTranfer { get; set; }
        public torder_bom? torder_bom { get; set; }
        public torder_bomTranfer? torder_bomTranfer { get; set; }
        public List<torder_bom>? Listtorder_bom { get; set; }
        public List<torder_bomTranfer>? Listtorder_bomTranfer { get; set; }
        public torder_bom_lp? torder_bom_lp { get; set; }
        public torder_bom_lpTranfer? torder_bom_lpTranfer { get; set; }
        public List<torder_bom_lp>? Listtorder_bom_lp { get; set; }
        public List<torder_bom_lpTranfer>? Listtorder_bom_lpTranfer { get; set; }
        public torder_bom_not_climp? torder_bom_not_climp { get; set; }
        public torder_bom_not_climpTranfer? torder_bom_not_climpTranfer { get; set; }
        public List<torder_bom_not_climp>? Listtorder_bom_not_climp { get; set; }
        public List<torder_bom_not_climpTranfer>? Listtorder_bom_not_climpTranfer { get; set; }
        public torder_bom_spst1? torder_bom_spst1 { get; set; }
        public torder_bom_spst1Tranfer? torder_bom_spst1Tranfer { get; set; }
        public List<torder_bom_spst1>? Listtorder_bom_spst1 { get; set; }
        public List<torder_bom_spst1Tranfer>? Listtorder_bom_spst1Tranfer { get; set; }
        public torder_bom_spst2? torder_bom_spst2 { get; set; }
        public torder_bom_spst2Tranfer? torder_bom_spst2Tranfer { get; set; }
        public List<torder_bom_spst2>? Listtorder_bom_spst2 { get; set; }
        public List<torder_bom_spst2Tranfer>? Listtorder_bom_spst2Tranfer { get; set; }
        public torder_bom_sw? torder_bom_sw { get; set; }
        public torder_bom_swTranfer? torder_bom_swTranfer { get; set; }
        public List<torder_bom_sw>? Listtorder_bom_sw { get; set; }
        public List<torder_bom_swTranfer>? Listtorder_bom_swTranfer { get; set; }
        public torder_lead_bom? torder_lead_bom { get; set; }
        public torder_lead_bomTranfer? torder_lead_bomTranfer { get; set; }
        public List<torder_lead_bom>? Listtorder_lead_bom { get; set; }
        public List<torder_lead_bomTranfer>? Listtorder_lead_bomTranfer { get; set; }
        public torder_lead_bom_excl? torder_lead_bom_excl { get; set; }
        public torder_lead_bom_exclTranfer? torder_lead_bom_exclTranfer { get; set; }
        public List<torder_lead_bom_excl>? Listtorder_lead_bom_excl { get; set; }
        public List<torder_lead_bom_exclTranfer>? Listtorder_lead_bom_exclTranfer { get; set; }
        public torder_lead_bom_spst? torder_lead_bom_spst { get; set; }
        public torder_lead_bom_spstTranfer? torder_lead_bom_spstTranfer { get; set; }
        public List<torder_lead_bom_spst>? Listtorder_lead_bom_spst { get; set; }
        public List<torder_lead_bom_spstTranfer>? Listtorder_lead_bom_spstTranfer { get; set; }
        public torder_lead_bom_spst_excl? torder_lead_bom_spst_excl { get; set; }
        public torder_lead_bom_spst_exclTranfer? torder_lead_bom_spst_exclTranfer { get; set; }
        public List<torder_lead_bom_spst_excl>? Listtorder_lead_bom_spst_excl { get; set; }
        public List<torder_lead_bom_spst_exclTranfer>? Listtorder_lead_bom_spst_exclTranfer { get; set; }
        public torder_spc? torder_spc { get; set; }
        public torder_spcTranfer? torder_spcTranfer { get; set; }
        public List<torder_spc>? Listtorder_spc { get; set; }
        public List<torder_spcTranfer>? Listtorder_spcTranfer { get; set; }
        public torderinspection? torderinspection { get; set; }
        public torderinspectionTranfer? torderinspectionTranfer { get; set; }
        public List<torderinspection>? Listtorderinspection { get; set; }
        public List<torderinspectionTranfer>? ListtorderinspectionTranfer { get; set; }
        public torderinspection_lp? torderinspection_lp { get; set; }
        public torderinspection_lpTranfer? torderinspection_lpTranfer { get; set; }
        public List<torderinspection_lp>? Listtorderinspection_lp { get; set; }
        public List<torderinspection_lpTranfer>? Listtorderinspection_lpTranfer { get; set; }
        public torderinspection_spst? torderinspection_spst { get; set; }
        public torderinspection_spstTranfer? torderinspection_spstTranfer { get; set; }
        public List<torderinspection_spst>? Listtorderinspection_spst { get; set; }
        public List<torderinspection_spstTranfer>? Listtorderinspection_spstTranfer { get; set; }
        public torderinspection_sw? torderinspection_sw { get; set; }
        public torderinspection_swTranfer? torderinspection_swTranfer { get; set; }
        public List<torderinspection_sw>? Listtorderinspection_sw { get; set; }
        public List<torderinspection_swTranfer>? Listtorderinspection_swTranfer { get; set; }
        public torderlist? torderlist { get; set; }
        public torderlistTranfer? torderlistTranfer { get; set; }
        public List<torderlist>? Listtorderlist { get; set; }
        public List<torderlistTranfer>? ListtorderlistTranfer { get; set; }
        public torderlist_lp? torderlist_lp { get; set; }
        public torderlist_lpTranfer? torderlist_lpTranfer { get; set; }
        public List<torderlist_lp>? Listtorderlist_lp { get; set; }
        public List<torderlist_lpTranfer>? Listtorderlist_lpTranfer { get; set; }
        public torderlist_lplist? torderlist_lplist { get; set; }
        public torderlist_lplistTranfer? torderlist_lplistTranfer { get; set; }
        public List<torderlist_lplist>? Listtorderlist_lplist { get; set; }
        public List<torderlist_lplistTranfer>? Listtorderlist_lplistTranfer { get; set; }
        public torderlist_spst? torderlist_spst { get; set; }
        public torderlist_spstTranfer? torderlist_spstTranfer { get; set; }
        public List<torderlist_spst>? Listtorderlist_spst { get; set; }
        public List<torderlist_spstTranfer>? Listtorderlist_spstTranfer { get; set; }
        public torderlist_sw? torderlist_sw { get; set; }
        public torderlist_swTranfer? torderlist_swTranfer { get; set; }
        public List<torderlist_sw>? Listtorderlist_sw { get; set; }
        public List<torderlist_swTranfer>? Listtorderlist_swTranfer { get; set; }
        public torderlist_work? torderlist_work { get; set; }
        public torderlist_workTranfer? torderlist_workTranfer { get; set; }
        public List<torderlist_work>? Listtorderlist_work { get; set; }
        public List<torderlist_workTranfer>? Listtorderlist_workTranfer { get; set; }
        public torderlist_wtime? torderlist_wtime { get; set; }
        public torderlist_wtimeTranfer? torderlist_wtimeTranfer { get; set; }
        public List<torderlist_wtime>? Listtorderlist_wtime { get; set; }
        public List<torderlist_wtimeTranfer>? Listtorderlist_wtimeTranfer { get; set; }
        public track_bc_tmp? track_bc_tmp { get; set; }
        public track_bc_tmpTranfer? track_bc_tmpTranfer { get; set; }
        public List<track_bc_tmp>? Listtrack_bc_tmp { get; set; }
        public List<track_bc_tmpTranfer>? Listtrack_bc_tmpTranfer { get; set; }
        public trackmaster? trackmaster { get; set; }
        public trackmasterTranfer? trackmasterTranfer { get; set; }
        public List<trackmaster>? Listtrackmaster { get; set; }
        public List<trackmasterTranfer>? ListtrackmasterTranfer { get; set; }
        public trackmtim? trackmtim { get; set; }
        public trackmtimTranfer? trackmtimTranfer { get; set; }
        public List<trackmtim>? Listtrackmtim { get; set; }
        public List<trackmtimTranfer>? ListtrackmtimTranfer { get; set; }
        public trackmtim_lt_insp? trackmtim_lt_insp { get; set; }
        public trackmtim_lt_inspTranfer? trackmtim_lt_inspTranfer { get; set; }
        public List<trackmtim_lt_insp>? Listtrackmtim_lt_insp { get; set; }
        public List<trackmtim_lt_inspTranfer>? Listtrackmtim_lt_inspTranfer { get; set; }
        public tsauth? tsauth { get; set; }
        public tsauthTranfer? tsauthTranfer { get; set; }
        public List<tsauth>? Listtsauth { get; set; }
        public List<tsauthTranfer>? ListtsauthTranfer { get; set; }
        public tsbom? tsbom { get; set; }
        public tsbomTranfer? tsbomTranfer { get; set; }
        public List<tsbom>? Listtsbom { get; set; }
        public List<tsbomTranfer>? ListtsbomTranfer { get; set; }
        public tsbom_list? tsbom_list { get; set; }
        public tsbom_listTranfer? tsbom_listTranfer { get; set; }
        public List<tsbom_list>? Listtsbom_list { get; set; }
        public List<tsbom_listTranfer>? Listtsbom_listTranfer { get; set; }
        public tsbom_part_inf? tsbom_part_inf { get; set; }
        public tsbom_part_infTranfer? tsbom_part_infTranfer { get; set; }
        public List<tsbom_part_inf>? Listtsbom_part_inf { get; set; }
        public List<tsbom_part_infTranfer>? Listtsbom_part_infTranfer { get; set; }
        public tsbom_po_list? tsbom_po_list { get; set; }
        public tsbom_po_listTranfer? tsbom_po_listTranfer { get; set; }
        public List<tsbom_po_list>? Listtsbom_po_list { get; set; }
        public List<tsbom_po_listTranfer>? Listtsbom_po_listTranfer { get; set; }
        public tsbom_ver02? tsbom_ver02 { get; set; }
        public tsbom_ver02Tranfer? tsbom_ver02Tranfer { get; set; }
        public List<tsbom_ver02>? Listtsbom_ver02 { get; set; }
        public List<tsbom_ver02Tranfer>? Listtsbom_ver02Tranfer { get; set; }
        public tsbom_ver02_po? tsbom_ver02_po { get; set; }
        public tsbom_ver02_poTranfer? tsbom_ver02_poTranfer { get; set; }
        public List<tsbom_ver02_po>? Listtsbom_ver02_po { get; set; }
        public List<tsbom_ver02_poTranfer>? Listtsbom_ver02_poTranfer { get; set; }
        public tsbom_ver02_tmp1? tsbom_ver02_tmp1 { get; set; }
        public tsbom_ver02_tmp1Tranfer? tsbom_ver02_tmp1Tranfer { get; set; }
        public List<tsbom_ver02_tmp1>? Listtsbom_ver02_tmp1 { get; set; }
        public List<tsbom_ver02_tmp1Tranfer>? Listtsbom_ver02_tmp1Tranfer { get; set; }
        public tscdgr? tscdgr { get; set; }
        public tscdgrTranfer? tscdgrTranfer { get; set; }
        public List<tscdgr>? Listtscdgr { get; set; }
        public List<tscdgrTranfer>? ListtscdgrTranfer { get; set; }
        public tscmpny? tscmpny { get; set; }
        public tscmpnyTranfer? tscmpnyTranfer { get; set; }
        public List<tscmpny>? Listtscmpny { get; set; }
        public List<tscmpnyTranfer>? ListtscmpnyTranfer { get; set; }
        public tscode? tscode { get; set; }
        public tscodeTranfer? tscodeTranfer { get; set; }
        public List<tscode>? Listtscode { get; set; }
        public List<tscode>? Listtscode01 { get; set; }
        public List<tscodeTranfer>? ListtscodeTranfer { get; set; }
        public tscost? tscost { get; set; }
        public tscostTranfer? tscostTranfer { get; set; }
        public List<tscost>? Listtscost { get; set; }
        public List<tscostTranfer>? ListtscostTranfer { get; set; }
        public tscost_list? tscost_list { get; set; }
        public tscost_listTranfer? tscost_listTranfer { get; set; }
        public List<tscost_list>? Listtscost_list { get; set; }
        public List<tscost_listTranfer>? Listtscost_listTranfer { get; set; }
        public tscut_st_uph? tscut_st_uph { get; set; }
        public tscut_st_uphTranfer? tscut_st_uphTranfer { get; set; }
        public List<tscut_st_uph>? Listtscut_st_uph { get; set; }
        public List<tscut_st_uphTranfer>? Listtscut_st_uphTranfer { get; set; }
        public tsmenu? tsmenu { get; set; }
        public tsmenuTranfer? tsmenuTranfer { get; set; }
        public List<tsmenu>? Listtsmenu { get; set; }
        public List<tsmenuTranfer>? ListtsmenuTranfer { get; set; }
        public tsmnau? tsmnau { get; set; }
        public tsmnauTranfer? tsmnauTranfer { get; set; }
        public List<tsmnau>? Listtsmnau { get; set; }
        public List<tsmnauTranfer>? ListtsmnauTranfer { get; set; }
        public tsmonitor_set? tsmonitor_set { get; set; }
        public tsmonitor_setTranfer? tsmonitor_setTranfer { get; set; }
        public List<tsmonitor_set>? Listtsmonitor_set { get; set; }
        public List<tsmonitor_setTranfer>? Listtsmonitor_setTranfer { get; set; }
        public tsnon_oper? tsnon_oper { get; set; }
        public tsnon_operTranfer? tsnon_operTranfer { get; set; }
        public List<tsnon_oper>? Listtsnon_oper { get; set; }
        public List<tsnon_operTranfer>? Listtsnon_operTranfer { get; set; }
        public tsnon_oper_andon? tsnon_oper_andon { get; set; }
        public tsnon_oper_andonTranfer? tsnon_oper_andonTranfer { get; set; }
        public List<tsnon_oper_andon>? Listtsnon_oper_andon { get; set; }
        public List<tsnon_oper_andonTranfer>? Listtsnon_oper_andonTranfer { get; set; }
        public tsnon_oper_andon_list? tsnon_oper_andon_list { get; set; }
        public tsnon_oper_andon_listTranfer? tsnon_oper_andon_listTranfer { get; set; }
        public List<tsnon_oper_andon_list>? Listtsnon_oper_andon_list { get; set; }
        public List<tsnon_oper_andon_listTranfer>? Listtsnon_oper_andon_listTranfer { get; set; }
        public tsnon_oper_mitor? tsnon_oper_mitor { get; set; }
        public tsnon_oper_mitorTranfer? tsnon_oper_mitorTranfer { get; set; }
        public List<tsnon_oper_mitor>? Listtsnon_oper_mitor { get; set; }
        public List<tsnon_oper_mitorTranfer>? Listtsnon_oper_mitorTranfer { get; set; }
        public tsnon_oper_worker? tsnon_oper_worker { get; set; }
        public tsnon_oper_workerTranfer? tsnon_oper_workerTranfer { get; set; }
        public List<tsnon_oper_worker>? Listtsnon_oper_worker { get; set; }
        public List<tsnon_oper_workerTranfer>? Listtsnon_oper_workerTranfer { get; set; }
        public tsnon_worktime? tsnon_worktime { get; set; }
        public tsnon_worktimeTranfer? tsnon_worktimeTranfer { get; set; }
        public List<tsnon_worktime>? Listtsnon_worktime { get; set; }
        public List<tsnon_worktimeTranfer>? Listtsnon_worktimeTranfer { get; set; }
        public tsnotice? tsnotice { get; set; }
        public tsnoticeTranfer? tsnoticeTranfer { get; set; }
        public List<tsnotice>? Listtsnotice { get; set; }
        public List<tsnoticeTranfer>? ListtsnoticeTranfer { get; set; }
        public tspart? tspart { get; set; }
        public tspartTranfer? tspartTranfer { get; set; }
        public List<tspart>? Listtspart { get; set; }
        public List<tspart>? Listtspart01 { get; set; }
        public List<tspart>? Listtspart02 { get; set; }
        public List<tspart>? Listtspart03 { get; set; }
        public List<tspartTranfer>? ListtspartTranfer { get; set; }
        public tspart_addtnl? tspart_addtnl { get; set; }
        public tspart_addtnlTranfer? tspart_addtnlTranfer { get; set; }
        public List<tspart_addtnl>? Listtspart_addtnl { get; set; }
        public List<tspart_addtnlTranfer>? Listtspart_addtnlTranfer { get; set; }
        public tspart_ecn? tspart_ecn { get; set; }
        public tspart_ecnTranfer? tspart_ecnTranfer { get; set; }
        public List<tspart_ecn>? Listtspart_ecn { get; set; }
        public List<tspart_ecnTranfer>? Listtspart_ecnTranfer { get; set; }
        public tspart_file? tspart_file { get; set; }
        public tspart_fileTranfer? tspart_fileTranfer { get; set; }
        public List<tspart_file>? Listtspart_file { get; set; }
        public List<tspart_fileTranfer>? Listtspart_fileTranfer { get; set; }
        public tsurau? tsurau { get; set; }
        public tsurauTranfer? tsurauTranfer { get; set; }
        public List<tsurau>? Listtsurau { get; set; }
        public List<tsurauTranfer>? ListtsurauTranfer { get; set; }
        public tsuser? tsuser { get; set; }
        public tsuserTranfer? tsuserTranfer { get; set; }
        public List<tsuser>? Listtsuser { get; set; }
        public List<tsuserTranfer>? ListtsuserTranfer { get; set; }
        public tsuser_requ? tsuser_requ { get; set; }
        public tsuser_requTranfer? tsuser_requTranfer { get; set; }
        public List<tsuser_requ>? Listtsuser_requ { get; set; }
        public List<tsuser_requTranfer>? Listtsuser_requTranfer { get; set; }
        public tsuser_super? tsuser_super { get; set; }
        public tsuser_superTranfer? tsuser_superTranfer { get; set; }
        public List<tsuser_super>? Listtsuser_super { get; set; }
        public List<tsuser_superTranfer>? Listtsuser_superTranfer { get; set; }
        public tsyear_group_inv? tsyear_group_inv { get; set; }
        public tsyear_group_invTranfer? tsyear_group_invTranfer { get; set; }
        public List<tsyear_group_inv>? Listtsyear_group_inv { get; set; }
        public List<tsyear_group_invTranfer>? Listtsyear_group_invTranfer { get; set; }
        public tsyear_group_inv_hist? tsyear_group_inv_hist { get; set; }
        public tsyear_group_inv_histTranfer? tsyear_group_inv_histTranfer { get; set; }
        public List<tsyear_group_inv_hist>? Listtsyear_group_inv_hist { get; set; }
        public List<tsyear_group_inv_histTranfer>? Listtsyear_group_inv_histTranfer { get; set; }
        public tsyear_inventory? tsyear_inventory { get; set; }
        public tsyear_inventoryTranfer? tsyear_inventoryTranfer { get; set; }
        public List<tsyear_inventory>? Listtsyear_inventory { get; set; }
        public List<tsyear_inventoryTranfer>? Listtsyear_inventoryTranfer { get; set; }
        public tsyear_inventory_hist? tsyear_inventory_hist { get; set; }
        public tsyear_inventory_histTranfer? tsyear_inventory_histTranfer { get; set; }
        public List<tsyear_inventory_hist>? Listtsyear_inventory_hist { get; set; }
        public List<tsyear_inventory_histTranfer>? Listtsyear_inventory_histTranfer { get; set; }
        public ttc_barcode? ttc_barcode { get; set; }
        public ttc_barcodeTranfer? ttc_barcodeTranfer { get; set; }
        public List<ttc_barcode>? Listttc_barcode { get; set; }
        public List<ttc_barcodeTranfer>? Listttc_barcodeTranfer { get; set; }
        public ttc_bom? ttc_bom { get; set; }
        public ttc_bomTranfer? ttc_bomTranfer { get; set; }
        public List<ttc_bom>? Listttc_bom { get; set; }
        public List<ttc_bomTranfer>? Listttc_bomTranfer { get; set; }
        public ttc_order? ttc_order { get; set; }
        public ttc_orderTranfer? ttc_orderTranfer { get; set; }
        public List<ttc_order>? Listttc_order { get; set; }
        public List<ttc_orderTranfer>? Listttc_orderTranfer { get; set; }
        public ttc_part? ttc_part { get; set; }
        public ttc_partTranfer? ttc_partTranfer { get; set; }
        public List<ttc_part>? Listttc_part { get; set; }
        public List<ttc_partTranfer>? Listttc_partTranfer { get; set; }
        public ttc_rackmtin? ttc_rackmtin { get; set; }
        public ttc_rackmtinTranfer? ttc_rackmtinTranfer { get; set; }
        public List<ttc_rackmtin>? Listttc_rackmtin { get; set; }
        public List<ttc_rackmtinTranfer>? Listttc_rackmtinTranfer { get; set; }
        public ttensilbndlst? ttensilbndlst { get; set; }
        public ttensilbndlstTranfer? ttensilbndlstTranfer { get; set; }
        public List<ttensilbndlst>? Listttensilbndlst { get; set; }
        public List<ttensilbndlstTranfer>? ListttensilbndlstTranfer { get; set; }
        public ttensilforce? ttensilforce { get; set; }
        public ttensilforceTranfer? ttensilforceTranfer { get; set; }
        public List<ttensilforce>? Listttensilforce { get; set; }
        public List<ttensilforceTranfer>? ListttensilforceTranfer { get; set; }
        public ttensilforce_usw? ttensilforce_usw { get; set; }
        public ttensilforce_uswTranfer? ttensilforce_uswTranfer { get; set; }
        public List<ttensilforce_usw>? Listttensilforce_usw { get; set; }
        public List<ttensilforce_uswTranfer>? Listttensilforce_uswTranfer { get; set; }
        public ttoolhistory? ttoolhistory { get; set; }
        public ttoolhistoryTranfer? ttoolhistoryTranfer { get; set; }
        public List<ttoolhistory>? Listttoolhistory { get; set; }
        public List<ttoolhistoryTranfer>? ListttoolhistoryTranfer { get; set; }
        public ttoolmaster? ttoolmaster { get; set; }
        public ttoolmasterTranfer? ttoolmasterTranfer { get; set; }
        public List<ttoolmaster>? Listttoolmaster { get; set; }
        public List<ttoolmasterTranfer>? ListttoolmasterTranfer { get; set; }
        public ttoolmaster2? ttoolmaster2 { get; set; }
        public ttoolmaster2Tranfer? ttoolmaster2Tranfer { get; set; }
        public List<ttoolmaster2>? Listttoolmaster2 { get; set; }
        public List<ttoolmaster2Tranfer>? Listttoolmaster2Tranfer { get; set; }
        public tuser_log? tuser_log { get; set; }
        public tuser_logTranfer? tuser_logTranfer { get; set; }
        public List<tuser_log>? Listtuser_log { get; set; }
        public List<tuser_logTranfer>? Listtuser_logTranfer { get; set; }
        public tuser_log_chk? tuser_log_chk { get; set; }
        public tuser_log_chkTranfer? tuser_log_chkTranfer { get; set; }
        public List<tuser_log_chk>? Listtuser_log_chk { get; set; }
        public List<tuser_log_chkTranfer>? Listtuser_log_chkTranfer { get; set; }
        public tuser_log_chk_list? tuser_log_chk_list { get; set; }
        public tuser_log_chk_listTranfer? tuser_log_chk_listTranfer { get; set; }
        public List<tuser_log_chk_list>? Listtuser_log_chk_list { get; set; }
        public List<tuser_log_chk_listTranfer>? Listtuser_log_chk_listTranfer { get; set; }
        public tworkresult? tworkresult { get; set; }
        public tworkresultTranfer? tworkresultTranfer { get; set; }
        public List<tworkresult>? Listtworkresult { get; set; }
        public List<tworkresultTranfer>? ListtworkresultTranfer { get; set; }
        public twtool? twtool { get; set; }
        public twtoolTranfer? twtoolTranfer { get; set; }
        public List<twtool>? Listtwtool { get; set; }
        public List<twtoolTranfer>? ListtwtoolTranfer { get; set; }
        public twwkar? twwkar { get; set; }
        public twwkarTranfer? twwkarTranfer { get; set; }
        public List<twwkar>? Listtwwkar { get; set; }
        public List<twwkarTranfer>? ListtwwkarTranfer { get; set; }
        public twwkar_lp? twwkar_lp { get; set; }
        public twwkar_lpTranfer? twwkar_lpTranfer { get; set; }
        public List<twwkar_lp>? Listtwwkar_lp { get; set; }
        public List<twwkar_lpTranfer>? Listtwwkar_lpTranfer { get; set; }
        public twwkar_spst? twwkar_spst { get; set; }
        public twwkar_spstTranfer? twwkar_spstTranfer { get; set; }
        public List<twwkar_spst>? Listtwwkar_spst { get; set; }
        public List<twwkar_spstTranfer>? Listtwwkar_spstTranfer { get; set; }
        public xsetting_time? xsetting_time { get; set; }
        public xsetting_timeTranfer? xsetting_timeTranfer { get; set; }
        public List<xsetting_time>? Listxsetting_time { get; set; }
        public List<xsetting_timeTranfer>? Listxsetting_timeTranfer { get; set; }
        public zadmin_function? zadmin_function { get; set; }
        public zadmin_functionTranfer? zadmin_functionTranfer { get; set; }
        public List<zadmin_function>? Listzadmin_function { get; set; }
        public List<zadmin_functionTranfer>? Listzadmin_functionTranfer { get; set; }
        public zt_devlpmnt_db? zt_devlpmnt_db { get; set; }
        public zt_devlpmnt_dbTranfer? zt_devlpmnt_dbTranfer { get; set; }
        public List<zt_devlpmnt_db>? Listzt_devlpmnt_db { get; set; }
        public List<zt_devlpmnt_dbTranfer>? Listzt_devlpmnt_dbTranfer { get; set; }
        public zt_help_db? zt_help_db { get; set; }
        public zt_help_dbTranfer? zt_help_dbTranfer { get; set; }
        public List<zt_help_db>? Listzt_help_db { get; set; }
        public List<zt_help_dbTranfer>? Listzt_help_dbTranfer { get; set; }
        public zt_log_db? zt_log_db { get; set; }
        public zt_log_dbTranfer? zt_log_dbTranfer { get; set; }
        public List<zt_log_db>? Listzt_log_db { get; set; }
        public List<zt_log_dbTranfer>? Listzt_log_dbTranfer { get; set; }
        public zz_mes_ver? zz_mes_ver { get; set; }
        public zz_mes_verTranfer? zz_mes_verTranfer { get; set; }
        public List<zz_mes_ver>? Listzz_mes_ver { get; set; }
        public List<zz_mes_verTranfer>? Listzz_mes_verTranfer { get; set; }
        public BaseModel()
        {
        }
    }
}
