namespace MESService.Model
{
    public partial class BaseParameter : BaseModel
    {
        public bool? CheckBox1 { get; set; }
        public bool? CheckBox2 { get; set; }
        public bool? CheckBox3 { get; set; }
        public bool? RadioButton1 { get; set; }
        public bool? RadioButton2 { get; set; }
        public bool? RadioButton3 { get; set; }
        public bool? RadioButton4 { get; set; }
        public bool? RadioButton5 { get; set; }
        public bool? RadioButton6 { get; set; }
        public bool? RadioButton7 { get; set; }
        public bool? RadioButton8 { get; set; }
        public bool? RadioButton9 { get; set; }
        public bool? RadioButton10 { get; set; }
        public bool? RadioButton11 { get; set; }
        public bool? RadioButton12 { get; set; }
        public bool? RadioButton13 { get; set; }
        public bool? RadioButton14 { get; set; }
        public bool? DGV_result3 { get; set; }
        public long? LineID { get; set; }
        public DateTime? Date { get; set; }
        public bool? Active { get; set; }
        public NGList? NGList { get; set; }
        public FAWorkOrder? FAWorkOrder { get; set; }
        public List<FAWorkOrder>? FAWorkOrderList { get; set; }
        public TaskTimeFA TaskTimeFA { get; set; }
        public List<TaskTimeFA> TaskTimeFAList { get; set; }
        public List<NGList>? NGLists { get; set; }
        public EmployeeFA EmployeeFA { get; set; }
        public List<EmployeeFA> EmployeeFAList { get; set; }
        public List<SuperResultTranfer>? DataGridView { get; set; }
        public List<SuperResultTranfer>? DataGridView1 { get; set; }
        public List<SuperResultTranfer>? DataGridView2 { get; set; }
        public List<SuperResultTranfer>? DataGridView3 { get; set; }
        public List<SuperResultTranfer>? DataGridView4 { get; set; }
        public List<SuperResultTranfer>? DataGridView5 { get; set; }
        public List<SuperResultTranfer>? DataGridView6 { get; set; }
        public List<SuperResultTranfer>? DataGridView7 { get; set; }
        public List<SuperResultTranfer>? DataGridView8 { get; set; }
        public List<V01_DMPS_COST>? V01_DMPS_COST_DataGridView3 { get; set; }
        public List<SuperResultTranfer>? T_DGV_02 { get; set; }
        public List<tspartTranfer>? DGV_LIST { get; set; }
        public List<tspartTranfer>? ListtspartTranfer { get; set; }
        public List<tspartTranfer>? DGV_G02_01 { get; set; }
        public List<tmbrcdTranfer>? ListtmbrcdTranfer01 { get; set; }
        public List<tmbrcdTranfer>? ListtmbrcdTranfer02 { get; set; }
        public int? Action { get; set; }
        public string? TabName { get; set; }     
        public string? WIRE { get; set; }     
        public string? Line { get; set; }     
        public List<B01>? ListB01 { get; set; }
        public string? USER_IDX { get; set; }
        public string? USER_ID { get; set; }
        public string? USER_NM { get; set; }
        public int? NON_OPER_IDX { get; set; }
        public bool IsRemember { get; set; }
        public int? Page { get; set; }
        public int? PageSize { get; set; }
        public string? SearchString { get; set; }
        public int? ID { get; set; }
        public int? ParentID { get; set; }
        public string? Code { get; set; }
        public string? Language { get; set; }
        public string? UserID { get; set; }
        public string? Password { get; set; }
        public string? IPAddress { get; set; }
        public DateTime? Begin { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? ToDate { get; set; }
        public int? Year { get; set; }
        public int? Month { get; set; }
        public List<int>? ListID { get; set; }
        public List<DateTime>? ListBegin { get; set; }
        public List<string>? ListSearchString { get; set; }
        public List<SuperResultTranfer>? SubPartItems { get; set; }
        public string? TabSelected { get; set; }
        public string? LeadNo { get; set; }
        public string? LotCode { get; set; }
        public string? GroupCode { get; set; }
        public string? GroupName { get; set; }
        public string Invoice { get; set; }
        public string ErrorInfo { get; set; }
        public string? StartDate { get; set; }
        public string? EndDate { get; set; }
        public string? TransactionType { get; set; }

        public string? FilterType { get; set; }
        public string? Barcode { get; set; }
        public string? PackingLotCode { get; set; }
        public string? TorqueBarcode { get; set; }
        public string? PartNo { get; set; }
        public string? PartName { get; set; }
        public string? PartEncno { get; set; }

        public bool? IsAdding { get; set; }
        public object? LeadData { get; set; }

        public int? Qty { get; set; }
        public int? BoxNumber { get; set; }
        public List<string>? Barcodes { get; set; }
        public int? PoQty { get; set; }
        public string? LeadNoGroup { get; set; }
        public bool? ReEntryConfirmed { get; set; }
        public string? CustomerCode { get; set; }

        public string? FilePath { get; set; }
        public string? Picture { get; set; }
        public string? PhysicalPath { get; set; }
        public string? Remark { get; set; }
        public string? ComboBox2 { get; set; }
        public string? ComboBox3 { get; set; }
        public string? ComboBox4 { get; set; }
        public string? DateTimePicker1 { get; set; }
        public string? DateTimePicker2 { get; set; }
        public string? DateTimePicker3 { get; set; }
        public string? ComboBox5 { get; set; }
        public string? ComboBox6 { get; set; }
        public string? ComboBox1 { get; set; }
        public string? TextBox1 { get; set; }
        public string? TextBox4 { get; set; }
        public string? Label37 { get; set; }
        public List<SuperResultTranfer>? DGV_OUT { get; set; }
        public string? TextBox3 { get; set; }
        public string? TextBox0 { get; set; }
        public string? TextBox2 { get; set; }
        public string? TextBox10 { get; set; }
        public string? TextBox11 { get; set; }
        public string? TextBox12 { get; set; }
        public int? CHK_SV { get; set; }
        public bool? BAR_NM_CHK { get; set; }
        public List<SuperResultTranfer>? DGV_C09_ST_00 { get; set; }
        public string? MC_NAME { get; set; }
        public bool? OR_NO_CHK { get; set; }
        public bool? CMPY_NO_CHK { get; set; }
        public string? PDPUSCH_IDX { get; set; }
        public string? TextBox5 { get; set; }
        public string? TextBox6 { get; set; }
        public string? TextBox7 { get; set; }
        public string? TextBox8 { get; set; }
        public string? TextBox9 { get; set; }
        public bool? RB_LH { get; set; }
        public bool? RB_RH { get; set; }
        public List<SuperResultTranfer> ImportData { get; set; }
        public string? EntryMethod { get; set; }
        public List<SuperResultTranfer>? Search { get; set; }
        public List<int>? C_MIN { get; set; }
        public bool? rb_Fac1 { get; set; }
        public bool? rb_Fac2 { get; set; }
        public bool? TM_CB1 { get; set; }
        public bool? TM_CB2 { get; set; }
        public bool? SL_CB1 { get; set; }
        public bool? WR_CB { get; set; }
        public string? TimeS { get; set; }
        public string? IsUsing { get; set; }
        public string? ShippNo { get; set; }
        public string? PalletNo { get; set; }
        public int? StartNumber { get; set; }
        public int? Length { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public string MACHINE_LIST { get; set; }
        public string MachineName { get; set; }
        public string EmployeeCode { get; set; }
        public string APIUpload { get; set; }
        public List<SuperResultTranfer>? DGV_C09_ST_BOM { get; set; }
        public string LineToAssign { get; set; }
        public int? ShiftID { get; set; }
        public bool SkipSNPCheck { get; set; }
        public bool? GP12 { get; set; }
        public string? ErrorID { get; set; }

        public long? MembershipID { get; set; }
        public long? CompanyID { get; set; }
        public long? CategoryDepartmentID { get; set; }
        public long? IDERP { get; set; }
        public string ReworkYN { get; set; }
        public string ShippingNo { get; set; }
        public string Destination { get; set; }
        public ToolShop? ToolShop { get; set; }
        public List<ToolShop>? ToolShopList { get; set; }
        public string? ProductionLine { get; set; }
        public string? Dept { get; set; }
        public string? Status { get; set; }
        public string? STOP_MC { get; set; }
        public string? CurrentStatus { get; set; }
        public string? Reason { get; set; }
        public string? Solution { get; set; }
        public string? SparePartsUsed { get; set; }
        public string? MaintenedBy { get; set; }
        public string? Notes { get; set; }
        public string? ToolShopSubCode { get; set; }
        public string Sub_Code { get; set; }
        public List<int>? Ids { get; set; }

        public List<WarehouseRequestDetail> ListWarehouseRequestDetail { get; set; }
        public string FilterFromDate { get; set; }
        public string FilterToDate { get; set; }
        public string? MONTH { get; set; }
        public string FilterDate { get; set; }
        public string SelectedDate { get; set; }
        public PartSpare? PartSpare { get; set; }
        public List<PartSpare>? PartSpareList { get; set; }
        public PartSpareScanIn? PartSpareScanIn { get; set; }
        public PartSpareScanOut? PartSpareScanOut { get; set; }
        public double Total { get;  set; }
        public double? TotalInvoice { get; set; }
        public double TotalNG { get;  set; }
        public string SearchText { get; set; }
        public string ImprovementPlans { get; set; }
        public string Note { get; set; }
        public MaintenanceHistory MaintenanceHistory { get; set; }
        public Trolley Trolley { get; set; }
        public List<Trolley> TrolleyList { get; set; }
        public IQCNGCustomer2? IQCNGCustomer2 { get; set; }
        public string Unit { get; set; }
        public BaseParameter()
        {
        }
    }
}
