namespace MESService.Model
{
    public partial class SuperResult : MESData.Model.BaseModel
    {        
        // Nguyên bản
        public int? ID { get; set; }
        public string? Name { get; set; }
        public string? Email { get; set; }
        public int? CDGR_IDX { get; set; }
        public string? CDGR_SYSNOTE { get; set; }
        public string? CDGR_NM_KR { get; set; }
        public string? CDGR_NM_ENG { get; set; }
        public DateTime? CREATE_DTM { get; set; }
        public string? CREATE_USER { get; set; }
        public DateTime? UPDATE_DTM { get; set; }
        public string? UPDATE_USER { get; set; }
        public int? CD_IDX { get; set; }
        public string? CD_SYS_NOTE { get; set; }
        public string? CD_NM_GRP { get; set; }
        public string? CD_NM { get; set; }
        public int? APQP_DLYLST_IDX { get; set; }
        public int? APQP_MSTLST_IDX { get; set; }
        public int? APQP_DLYLST_RNK { get; set; }
        public DateTime? APQP_DLYLST_NXTDT { get; set; }
        public string? APQP_DLYLST_NM { get; set; }
        public int? APQP_FLLST_IDX { get; set; }
        public int? APQP_FLLST_RNK { get; set; }
        public DateTime? APQP_FLLST_DATE { get; set; }
        public string? APQP_FLLST_RVW { get; set; }
        public string? APQP_FLLST_NM { get; set; }
        public string? APQP_FLLST_ETN { get; set; }
        public string? APQP_FLLST_SIZE { get; set; }
        public int? APQP_MS_IDX { get; set; }
        public int? APQP_CSTM { get; set; }
        public int? APQP_MS_RNK { get; set; }
        public int? APQP_MS_PRJT { get; set; }
        public string? APQP_MS_CODE0 { get; set; }
        public int? APQP_MS_CODE1 { get; set; }
        public int? APQP_MS_CODE2 { get; set; }
        public int? APQP_MS_CODE3 { get; set; }
        public string? APQP_MS_NM { get; set; }
        public string? APQP_MS_TM { get; set; }
        public int? APQP_MS_USER { get; set; }
        public DateTime? APQP_MS_SDT { get; set; }
        public DateTime? APQP_MS_EDT { get; set; }
        public string? APQP_MS_DSYN { get; set; }
        public string? APQP_MS_NOTE { get; set; }
        public string? APQP_MS_REMARK { get; set; }
        public string? APQP_MS_FLDSYN { get; set; }
        public string? APQP_MS_FILE { get; set; }
        public int? KR_INSPCTN_IDX { get; set; }
        public int? KR_INSPCTN_PARTIDX { get; set; }
        public string? KR_INSPCTN_EO { get; set; }
        public int? KR_INSPCTN_VER { get; set; }
        public DateTime? KR_INSPCTN_DATE { get; set; }
        public int? KR_INSPCTN_NO { get; set; }
        public string? KR_INSPCTN_TEXT { get; set; }
        public double? KR_INSPCTN_ST { get; set; }
        public double? KR_INSPCTN_MIN { get; set; }
        public double? KR_INSPCTN_MAX { get; set; }
        public int? KR_INSPCTN_TEST_IDX { get; set; }
        public string? KR_INSPCTN_CODE { get; set; }
        public string? KR_INSPCTN_N { get; set; }
        public double? KR_INSPCTN_X1 { get; set; }
        public double? KR_INSPCTN_X2 { get; set; }
        public double? KR_INSPCTN_X3 { get; set; }
        public double? KR_INSPCTN_X4 { get; set; }
        public double? KR_INSPCTN_X5 { get; set; }
        public string? KR_INSPCTN_RUS { get; set; }
        public int? TDD_PP_IDX { get; set; }
        public string? TDD_PO_TYPE { get; set; }
        public string? TDD_POCODE { get; set; }
        public int? TDD_POCSTM { get; set; }
        public int? TDD_PP_PNIDX { get; set; }
        public DateTime? TDD_PP_DT { get; set; }
        public int? TDD_PP_QTY { get; set; }
        public int? TDD_PP_PACK { get; set; }
        public string? TDD_DSCN_YN { get; set; }
        public string? TDD_REMARK { get; set; }
        public int? PDMTIN_IDX { get; set; }
        public int? VLID_PART_IDX { get; set; }
        public int? VLID_PART_SNP { get; set; }
        public string? VLID_GRP { get; set; }
        public DateTime? VLID_DTM { get; set; }
        public string? VLID_BARCODE { get; set; }
        public string? VLID_REMARK { get; set; }
        public string? TDPDOTPLMU { get; set; }
        public string? PDOTPL_VNPOCODE { get; set; }
        public int? PDOTPL_IDX { get; set; }
        public int? TSCOST_IDX { get; set; }
        public string? BARCD_LOC { get; set; }
        public string? VLID_DSCN_YN { get; set; }
        public string? INSPCTN_YN { get; set; }
        public string? INSPCTN_GRUP_CODE { get; set; }
        public int? KR_TDPDMTIN_IDX { get; set; }
        public string? KR_TDPDMTIN_POCODE { get; set; }
        public string? KR_TDPDMTIN_PLTNO { get; set; }
        public string? KR_TDPDMTIN_PART_NO { get; set; }
        public int? KR_TDPDMTIN_SNP { get; set; }
        public string? KR_TDPDMTIN_VLID_GRP { get; set; }
        public DateTime? KR_TDPDMTIN_DTM { get; set; }
        public string? KR_TDPDMTIN_BARCODE { get; set; }
        public string? KR_TDPDMTIN_REMARK { get; set; }
        public string? KR_TDPDMTIN_DSNY { get; set; }
        public string? KR_TDPDMTIN_GRUPCD { get; set; }
        public string? KR_TDPDMTIN_INSPNY { get; set; }
        public int? KR_TDPDMTIN_MIDX { get; set; }
        public string? PO_CODE { get; set; }
        public int? PART_IDX { get; set; }
        public int? PART_IDX_SNP { get; set; }
        public int? PO_QTY { get; set; }
        public int? NT_QTY { get; set; }
        public int? PACK_QTY { get; set; }
        public string? DONE_YN { get; set; }
        public int? SORTNO { get; set; }
        public int? PDOTPL_INPO_IDX { get; set; }
        public string? PART_NO { get; set; }
        public int? PART_SNP { get; set; }
        public int? IN_QTY { get; set; }
        public int? IV_IDX { get; set; }
        public int? LOC_IDX { get; set; }
        public double? QTY { get; set; }
        public double? STOP_TIME { get; set; }
        public double? T_STOP { get; set; }
        public int? PD_ASSET_IDX { get; set; }
        public string? PDP_ASSET_ID { get; set; }
        public DateTime? PDP_ASSET_INDATE { get; set; }
        public string? PDP_ASSET_NAME { get; set; }
        public string? PDP_ASSET_SPC { get; set; }
        public int? PDP_DEPA { get; set; }
        public string? PDP_DEPA_USER { get; set; }
        public DateTime? PDP_DEPA_USERDT { get; set; }
        public string? PDP_DEPA_DYN { get; set; }
        public int? PD_CMPNY_PART_IDX { get; set; }
        public int? CMPNY_IDX { get; set; }
        public DateTime? COST_DATE { get; set; }
        public string? COST_FILENM { get; set; }
        public string? COST_FILETYPE { get; set; }
        public string? REMARK { get; set; }
        public string? DSN_YN { get; set; }
        public int? PDPART_IDX { get; set; }
        public string? DSC_YN { get; set; }
        public int? PD_INPUT_PART_IDX { get; set; }
        public int? ORDER_IDX { get; set; }
        public string? DSC_INOUT { get; set; }
        public int? PUR_QTY { get; set; }
        public DateTime? PUR_TIME { get; set; }
        public string? OUT_USER { get; set; }
        public int? PD_MC_ORDER_IDX { get; set; }
        public int? PD_PART_IDX { get; set; }
        public DateTime? PD_PURDATE { get; set; }
        public int? PD_MC_NO { get; set; }
        public int? PD_MC_QTY { get; set; }
        public string? PD_MC_UNIT { get; set; }
        public double? PD_MC_COST { get; set; }
        public string? PD_BYORDER { get; set; }
        public string? PD_MC_CMPYNM { get; set; }
        public string? PD_MC_STAY { get; set; }
        public string? PD_MC_APP { get; set; }
        public string? PD_MC_REMARK { get; set; }
        public string? PD_ORDER_NO { get; set; }
        public DateTime? PD_MC_ODDATE { get; set; }
        public double? PD_PAYCOST { get; set; }
        public string? PD_MC_DSN_YN { get; set; }
        public int? PDCOST_IDX { get; set; }
        public DateTime? PD_COST_DATE { get; set; }
        public string? PD_COST { get; set; }
        public string? IMP_YN { get; set; }
        public string? CDGR_NM_VN { get; set; }
        public string? CDGR_NM_HAN { get; set; }
        public string? CD_NM_VN { get; set; }
        public string? CD_NM_HAN { get; set; }
        public string? CMPNY_NM { get; set; }
        public string? CMPNY_DVS { get; set; }
        public string? CMPNY_NO { get; set; }
        public string? CMPNY_ADDR { get; set; }
        public string? CMPNY_TEL { get; set; }
        public string? CMPNY_FAX { get; set; }
        public string? CMPNY_MNGR { get; set; }
        public string? CMPNY_RMK { get; set; }
        public string? PN_V { get; set; }
        public string? PSPEC_V { get; set; }
        public string? PN_K { get; set; }
        public string? PSPEC_K { get; set; }
        public string? PN_NM { get; set; }
        public int? PUNIT_IDX { get; set; }
        public double? PQTY { get; set; }
        public string? PN_DSCN_YN { get; set; }
        public string? PN_GROUP { get; set; }
        public string? PN_PHOTO { get; set; }
        public int? PDPART_AL_IDX { get; set; }
        public string? PN_NM_AL { get; set; }
        public string? PN_V_AL { get; set; }
        public string? PSPEC_V_AL { get; set; }
        public string? PN_K_AL { get; set; }
        public string? PSPEC_K_AL { get; set; }
        public double? PQTY_AL { get; set; }
        public int? PDPUSCH_IDX { get; set; }
        public string? PDP_CONF { get; set; }
        public string? PDP_FACT { get; set; }
        public long? PDP_NO { get; set; }
        public string? PDP_COMPY_NO { get; set; }
        public DateTime? PDP_DATE1 { get; set; }
        public int? PDP_PART { get; set; }
        public int? PDP_QTY { get; set; }
        public string? PDP_MEMO { get; set; }
        public string? PDP_REC_YN { get; set; }
        public int? PDP_CMPY { get; set; }
        public DateTime? PDP_DATE2 { get; set; }
        public double? PDP_COST { get; set; }
        public double? PDP_VAT { get; set; }
        public double? PDP_ECTCOST { get; set; }
        public double? PDP_TOTCOST { get; set; }
        public DateTime? PDP_CNF_DATE { get; set; }
        public string? PDP_CNF_YN { get; set; }
        public string? PDP_ORD_ST { get; set; }
        public string? PDP_REMARK { get; set; }
        public double? PDP_BE_COST { get; set; }
        public DateTime? PDP_INCO_DT { get; set; }
        public int? PDP_IN_QTY { get; set; }
        public string? PDP_FIFO { get; set; }
        public string? PDP_PRIENT { get; set; }
        public int? TDD_CT_IDX { get; set; }
        public int? TDD_CT_PNIDX { get; set; }
        public DateTime? TDD_CT_DT { get; set; }
        public double? TDD_CT_QTY { get; set; }
        public double? TDD_CT_SUB { get; set; }
        public double? TDD_CT_FA { get; set; }
        public double? TDD_CT_RO { get; set; }
        public double? TDD_MPP { get; set; }
        public DateTime? TDD_CT_BEDT { get; set; }
        public double? TDD_CT_BEQTY { get; set; }
        public int? TDD_PP_NTQTY { get; set; }
        public string? TDD_REMK_YN { get; set; }
        public int? TDD_PPD_IDX { get; set; }
        public int? TDD_PPD_PNIDX { get; set; }
        public DateTime? TDD_PPD_DT { get; set; }
        public string? TDD_PPD_DVC { get; set; }
        public int? TDD_PPD_QTY { get; set; }
        public int? TDD_PPD_BEQTY { get; set; }
        public int? TDPDOTPLMU_IDX { get; set; }
        public int? PDMTINABC_IDX { get; set; }
        public int? PDMTINABC_PRT_IDX { get; set; }
        public string? PDMTN_BARCODE { get; set; }
        public string? PDMTINABC_DSCN_YN { get; set; }
        public int? TDLOC_IDX { get; set; }
        public int? TDLOC_PART_IDX { get; set; }
        public string? TDLOC_PARTNO { get; set; }
        public string? TDLOC_COSM { get; set; }
        public string? TDLOC_MOQ { get; set; }
        public string? TDLOC_PARTNM { get; set; }
        public string? TDLOC_LOC { get; set; }
        public string? TDLOC_REMARK { get; set; }
        public int? PDTMP_IDX { get; set; }
        public int? TDPDMTIN_SERIAL_IDX { get; set; }
        public DateTime? TDPD_DATE { get; set; }
        public int? SEQ_NO { get; set; }
        public string? SERIAL_NO { get; set; }
        public string? D_ARRVL { get; set; }
        public int? TDPDOTPL_ETC_IDX { get; set; }
        public string? ETC_PO_CODE { get; set; }
        public DateTime? DATE { get; set; }
        public DateTime? PDLB_DATE { get; set; }
        public int? LABEL_NO { get; set; }
        public string? LABEL_TXT { get; set; }
        public string? PLET_NO { get; set; }
        public string? PLET_COMS { get; set; }
        public DateTime? PDOTPL_DTM { get; set; }
        public int? SE_QTY { get; set; }
        public string? DSCN_YN { get; set; }
        public int? TFG_MO_IDX { get; set; }
        public DateTime? TFG_DATE { get; set; }
        public int? TFG_CD_IDX { get; set; }
        public int? TFG_QTY { get; set; }
        public int? TFG_QTYBOX { get; set; }
        public int? TFG_TOTL_QTY { get; set; }
        public int? TFG_TOTL_QTYBOX { get; set; }
        public string? TFG_NTC { get; set; }
        public int? IVAJ_IDX { get; set; }
        public int? ADJ_SCN { get; set; }
        public DateTime? ADJ_DTM { get; set; }
        public double? ADJ_QTY { get; set; }
        public double? ADJ_BF_QTY { get; set; }
        public double? ADJ_AF_QTY { get; set; }
        public string? ADJ_RSON { get; set; }
        public DateTime? STOCK_DATE { get; set; }
        public int? BARCD_IDX { get; set; }
        public string? BARCD_ID { get; set; }
        public string? PKG_GRP_IDX { get; set; }
        public string? PKG_GRP { get; set; }
        public double? PKG_QTY { get; set; }
        public double? PKG_OUTQTY { get; set; }
        public DateTime? OUT_DTM { get; set; }
        public int? MTIN_IDX { get; set; }
        public string? BBCO { get; set; }
        public int? TMBRCD_LONGTERM_IDX { get; set; }
        public int? LT_BARCD_IDX { get; set; }
        public DateTime? LT_INS_DATE { get; set; }
        public string? LT_RUS { get; set; }
        public string? LT_STAY { get; set; }
        public string? UTM { get; set; }
        public string? DESC { get; set; }
        public decimal? NET_WT { get; set; }
        public decimal? GRS_WT { get; set; }
        public string? SHPD_NO { get; set; }
        public DateTime? MTIN_DTM { get; set; }
        public string? BRCD_PRNT { get; set; }
        public string? MTIN_RMK { get; set; }
        public int? SNP_QTY { get; set; }
        public int? TMMTIN_DMM_IDX { get; set; }
        public int? TMMTIN_DMM_STGC { get; set; }
        public DateTime? TMMTIN_DATE { get; set; }
        public string? TMMTIN_CODE { get; set; }
        public int? TMMTIN_PART { get; set; }
        public int? TMMTIN_PART_SNP { get; set; }
        public string? TMMTIN_QTY { get; set; }
        public string? TMMTIN_REC_YN { get; set; }
        public string? TMMTIN_CNF_YN { get; set; }
        public string? TMMTIN_DSCN_YN { get; set; }
        public int? TMMTIN_SHEETNO { get; set; }
        public string? TMMTIN_MTORDR { get; set; }
        public int? TMMTIN_ORDERNO { get; set; }
        public int? TORDER_BARCODE_IDX { get; set; }
        public string? TORDER_BARCODENM { get; set; }
        public int? Barcode_SEQ { get; set; }
        public string? TORDER_BC_PRNT { get; set; }
        public string? TORDER_BC_WORK { get; set; }
        public DateTime? WORK_START { get; set; }
        public DateTime? WORK_END { get; set; }
        public int? TORDER_BOM_IDX { get; set; }
        public int? T1_TOOL_IDX { get; set; }
        public int? T2_TOOL_IDX { get; set; }
        public string? ERROR_CHK { get; set; }
        public int? CLIMP_IDX { get; set; }
        public string? CLIMP_TERM { get; set; }
        public int? TORDER_BOMSPST_IDX { get; set; }
        public double? BARCODE_QTY { get; set; }
        public double? USE_QTY { get; set; }
        public int? TORDER_BOMSPST2_IDX { get; set; }
        public int? TORDER_SPSTORDER_IDX { get; set; }
        public string? LOC_LRJ { get; set; }
        public double? PERFORMN { get; set; }
        public int? LEAD_INDEX { get; set; }
        public string? LEAD_SCN { get; set; }
        public string? LEAD_PN { get; set; }
        public int? BUNDLE_SIZE { get; set; }
        public int? W_PN_IDX { get; set; }
        public int? T1_PN_IDX { get; set; }
        public int? S1_PN_IDX { get; set; }
        public int? T2_PN_IDX { get; set; }
        public int? S2_PN_IDX { get; set; }
        public string? STRIP1 { get; set; }
        public string? STRIP2 { get; set; }
        public string? CCH_W1 { get; set; }
        public string? ICH_W1 { get; set; }
        public string? CCH_W2 { get; set; }
        public string? ICH_W2 { get; set; }
        public string? T1NO { get; set; }
        public string? T2NO { get; set; }
        public string? W_LINK { get; set; }
        public string? WR_NO { get; set; }
        public string? WIRE_NM { get; set; }
        public string? W_Diameter { get; set; }
        public string? W_Color { get; set; }
        public double? W_Length { get; set; }
        public string? HOOK_RACK { get; set; }
        public string? SFTY_STK { get; set; }
        public int? SPST_IDX { get; set; }
        public int? M_PART_IDX { get; set; }
        public int? S_PART_IDX { get; set; }
        public int? RQR_MENT { get; set; }
        public string? S_LR { get; set; }
        public int? SPC_IDX { get; set; }
        public string? SPC_GRP { get; set; }
        public int? LEAD_IDX { get; set; }
        public int? TERM_IDX { get; set; }
        public DateTime? SPC_DATE { get; set; }
        public double? SPC_ST { get; set; }
        public double? SPC_MIN { get; set; }
        public double? SPC_MAX { get; set; }
        public double? CCH_XN { get; set; }
        public int? INSPECTION_IDX { get; set; }
        public string? COLSIP { get; set; }
        public double? CCH1 { get; set; }
        public double? CCW1 { get; set; }
        public double? CCH2 { get; set; }
        public double? CCW2 { get; set; }
        public double? ICH1 { get; set; }
        public double? ICW1 { get; set; }
        public double? ICH2 { get; set; }
        public double? ICW2 { get; set; }
        public double? WIRE_FORCE { get; set; }
        public int? WIRE_LENGTH { get; set; }
        public string? IN_RESILT { get; set; }
        public string? CHK_LR { get; set; }
        public double? RES_H { get; set; }
        public double? RES_V { get; set; }
        public double? CCH { get; set; }
        public double? CCW { get; set; }
        public double? ICH { get; set; }
        public double? ICW { get; set; }
        public string? OR_NO { get; set; }
        public int? WORK_WEEK { get; set; }
        public string? LEAD_NO { get; set; }
        public string? PROJECT { get; set; }
        public double? TOT_QTY { get; set; }
        public string? CUR_LEADS { get; set; }
        public string? CT_LEADS { get; set; }
        public string? CT_LEADS_PR { get; set; }
        public string? GRP { get; set; }
        public string? PRT { get; set; }
        public DateTime? DT { get; set; }
        public string? MC { get; set; }
        public string? MC2 { get; set; }
        public string? WIRE { get; set; }
        public string? T1_DIR { get; set; }
        public string? TERM1 { get; set; }
        public string? SEAL1 { get; set; }
        public string? T2_DIR { get; set; }
        public string? TERM2 { get; set; }
        public string? SEAL2 { get; set; }
        public string? SP_ST { get; set; }
        public string? REP { get; set; }
        public string? CONDITION { get; set; }
        public string? FCTRY_NM { get; set; }
        public string? MTRL_RQUST { get; set; }
        public string? TORDER_FG { get; set; }
        public double? TOEXCEL_QTY { get; set; }
        public double? PERFORMN_L { get; set; }
        public double? PERFORMN_R { get; set; }
        public int? TORDERLIST_LPLIST_IDX { get; set; }
        public string? LPLIST_LEADNO { get; set; }
        public string? LPLIST_DYN { get; set; }
        public DateTime? PO_DT { get; set; }
        public double? SAFTY_QTY { get; set; }
        public int? LEAD_COUNT { get; set; }
        public string? PO_YN { get; set; }
        public string? ERROR_YN { get; set; }
        public int? TORDERLIST_WORK_IDX { get; set; }
        public string? TORDERLIST_WORK_MC { get; set; }
        public int? TORDERLIST_WORK_ORDERIDX { get; set; }
        public string? TORDERLIST_WORK_USER { get; set; }
        public int? TOWT_INDX { get; set; }
        public string? MENU_TEXT { get; set; }
        public string? USER_ID { get; set; }
        public string? USER_MC { get; set; }
        public DateTime? S_TIME { get; set; }
        public DateTime? E_TIME { get; set; }
        public int? TRACK_BC_IDX { get; set; }
        public string? TRACK_BC_LEAD { get; set; }
        public string? TRACK_BC_NAME { get; set; }
        public int? RACK_IDX { get; set; }
        public string? SP { get; set; }
        public int? TRACK_IDX { get; set; }
        public string? RACKCODE { get; set; }
        public int? TABLE_IDX { get; set; }
        public string? TABLE_NM { get; set; }
        public string? LEAD_NM { get; set; }
        public string? BARCODE_NM { get; set; }
        public DateTime? RACKDTM { get; set; }
        public DateTime? RACKOUT_DTM { get; set; }
        public string? RACKIN_YN { get; set; }
        public string? RACKOUT_YN { get; set; }
        public int? LT_INSP_IDX { get; set; }
        public int? TRACKMTIN_IDX { get; set; }
        public DateTime? INSP_DATE { get; set; }
        public int? INSP_QTY { get; set; }
        public int? OK_QTY { get; set; }
        public int? NG_QTY { get; set; }
        public string? INSP_RESULT { get; set; }
        public int? AUTH_IDX { get; set; }
        public string? AUTH_ID { get; set; }
        public string? AUTH_NM { get; set; }
        public int? BOM_IDX { get; set; }
        public int? PAREN_PART_IDX { get; set; }
        public double? BOM_US { get; set; }
        public string? BOM_DSYN { get; set; }
        public string? BOM_REMARK { get; set; }
        public int? BOM_LIST_IDX { get; set; }
        public string? PAREN_PART_NO { get; set; }
        public string? PART_NONM { get; set; }
        public string? BOM_DES { get; set; }
        public string? BOM_UNIT { get; set; }
        public string? BOM_GRUP { get; set; }
        public string? BOM_RMK { get; set; }
        public int? INF_BOM_IDX { get; set; }
        public int? INF_PART_IDX { get; set; }
        public string? INF_PART_NONM { get; set; }
        public string? INF_BOM_UNIT { get; set; }
        public string? INF_BOM_MAKER { get; set; }
        public double? INF_BOM_WEIGHT { get; set; }
        public string? INF_BOM_COLOR { get; set; }
        public string? INF_BOM_MOQ { get; set; }
        public string? INF_BOM_RMK { get; set; }
        public int? BOM_PO_LIST_IDX { get; set; }


        public string? DSYN { get; set; }
        public int? PAREN_EO_IDX { get; set; }
        public int? LV_NO { get; set; }
        public DateTime? PO_DATE { get; set; }
        public string? PO_GRUP { get; set; }
        public string? PAREN_EO_NO { get; set; }
        public string? CDGR_NM_EN { get; set; }       
        
        public string? CD_NM_EN { get; set; }
        public int? TSPSRT_IDX { get; set; }
        public DateTime? TSCOST_DT { get; set; }
        public double? TSCOST_VAL { get; set; }
        public int? TSCUT_ST_UPH_IDX { get; set; }
        public string? TSCUT_ST_UPH_RUT { get; set; }
        public string? TSCUT_ST_UPH_NAME { get; set; }
        public double? TSCUT_ST_UPH_MIN { get; set; }
        public double? TSCUT_ST_UPH_MAX { get; set; }
        public double? TSCUT_ST_UPH_TCNT { get; set; }
        public double? TSCUT_ST_UPH_SCNT { get; set; }
        public double? TSCUT_ST_UPH_RUS { get; set; }



        public int? MENU_IDX { get; set; }
        public int? MENU_CD { get; set; }
        public int? MENU_LVL { get; set; }
        public string? MENU_NM_EN { get; set; }
        public string? MENU_NM_HAN { get; set; }
        public int? MENU_NM_VIE_ID { get; set; }
        public string? SCRN_PATH { get; set; }
        public string? DECYN { get; set; }
        public int? MENU_AUTH_IDX { get; set; }
        public string? MENU_AUTH_YN { get; set; }
        public string? IQ_AUTH_YN { get; set; }
        public string? RGST_AUTH_YN { get; set; }
        public string? MDFY_AUTH_YN { get; set; }
        public string? DEL_AUTH_YN { get; set; }
        public string? CAN_AUTH_YN { get; set; }
        public string? EXCL_AUTH_YN { get; set; }
        public string? DNLD_AUTH_YN { get; set; }
        public string? PRNT_AUTH_YN { get; set; }
        public string? ETC1_AUTH_YN { get; set; }
        public string? ETC2_AUTH_YN { get; set; }
        public string? ETC3_AUTH_YN { get; set; }
        public int? TSMONITOR_SET_IDX { get; set; }
        public int? TSMONITOR_SET_NO { get; set; }
        public string? TSMONITOR_SET_CODE { get; set; }
        public string? VB_NAME { get; set; }
        public string? VB_NAME_KR { get; set; }
        public string? VB_NAME_ENG { get; set; }
        public string? VB_NAME_VN { get; set; }
        public string? VB_CHK_YN { get; set; }
        public int? VB_CY_COUNT { get; set; }
        public int? VB_TIME { get; set; }
        public int? TSNON_OPER_IDX { get; set; }
        public string? TSNON_OPER_CODE { get; set; }
        public string? TSNON_OPER_MCNM { get; set; }
        public string? TSNON_OPER_USERNM { get; set; }
        public DateTime? TSNON_OPER_DATE { get; set; }
        public DateTime? TSNON_OPER_STIME { get; set; }
        public DateTime? TSNON_OPER_ETIME { get; set; }
        public int? TSNON_OPER_TIME { get; set; }
        public int? TSNON_OPER_MITOR_IDX { get; set; }
        public string? tsnon_oper_mitor_MCNM { get; set; }
        public string? tsnon_oper_mitor_NOIC { get; set; }
        public string? tsnon_oper_mitor_RUNYN { get; set; }
        public string? TSNON_OPER_COL { get; set; }
        public int? TSNON_WT_IDX { get; set; }
        public int? TSNON_MCIDX { get; set; }
        public int? TSNON_SHIF { get; set; }
        public DateTime? TSNON_DATE { get; set; }
        public DateTime? TSNON_ST { get; set; }
        public DateTime? TSNON_ET { get; set; }
        public int? Notice_IDX { get; set; }
        public string? Title { get; set; }
        public string? Contents { get; set; }
        public string? PART_NM { get; set; }
        public string? BOM_GRP { get; set; }
        public string? PART_CAR { get; set; }
        public string? PART_FML { get; set; }
        public int? PART_SCN { get; set; }
        public string? PART_LOC { get; set; }
        public string? PART_USENY { get; set; }
        public string? PART_RMK { get; set; }
        public string? PART_SUPL { get; set; }
        public int? PART_ADDTNL_IDX { get; set; }
        public int? PARTNO_IDX { get; set; }
        public double? OP_W { get; set; }
        public double? OP_L { get; set; }
        public double? OP_H { get; set; }
        public double? OP_MRP { get; set; }
        public string? OP_TMP1 { get; set; }
        public string? OP_TMP2 { get; set; }
        public string? OP_TMP3 { get; set; }
        public double? Weight { get; set; }
        public int? PARTECN_IDX { get; set; }
        public string? PART_ENCNO { get; set; }
        public DateTime? PART_ECN_DATE { get; set; }
        public string? DWG_NO { get; set; }
        public string? DWG_FILE_GRP { get; set; }
        public string? DWG_FILE_EXPOR { get; set; }
        public string? PART_ECN_USENY { get; set; }
        public int? PARTFILE_IDX { get; set; }
        public int? FILE_NO { get; set; }
        public string? FILE_FOLDER { get; set; }
        public string? FILE_NAME { get; set; }
        public string? FILE_REMARK { get; set; }
        public string? FILE_USEYN { get; set; }
        public int? USER_AUTH_IDX { get; set; }
        public int? USER_IDX { get; set; }
        public string? USER_NM { get; set; }
        public string? PW { get; set; }
        public string? Dept { get; set; }
        public string? Note { get; set; }
        public string? DESC_YN { get; set; }
        public int? REQU_IDX { get; set; }
        public string? REQU_ID { get; set; }
        public DateTime? REQU_DATE { get; set; }
        public string? REQU_NOTE { get; set; }
        public string? REQU_NID { get; set; }
        public string? REQU_NAME { get; set; }
        public string? REQU_DEP { get; set; }
        public string? REQU_TSAUTH { get; set; }
        public string? REQU_DES { get; set; }
        public string? REQU_APP { get; set; }
        public string? USER_ID_NAME { get; set; }
        public string? NAS_TEST_SER { get; set; }
        public string? LOC_TEST_SER { get; set; }
        public int? TSYEAR_GROUP_IDX { get; set; }
        public string? TSYEAR_YEAR { get; set; }
        public int? TSYEAR_MESNO { get; set; }
        public string? TSYEAR_DEPART { get; set; }
        public string? TSYEAR_PKILOC { get; set; }
        public string? TSYEAR_INPUTER { get; set; }
        public int? TSYEAR_SERIAL_NO1 { get; set; }
        public int? TSYEAR_SERIAL_NO2 { get; set; }
        public int? TSYEAR_INV_IDX { get; set; }
        public string? TSYEAR_INV_YEAR { get; set; }
        public int? TSYEAR_INV_SERIALNO { get; set; }
        public string? TSYEAR_INV_DEPART { get; set; }
        public string? TSYEAR_INV_PKILOC { get; set; }
        public string? TSYEAR_INV_PART_TNM { get; set; }
        public int? TSYEAR_INV_PART_IDX { get; set; }
        public int? TSYEAR_INV_QTY { get; set; }
        public string? TSYEAR_INV_DSNY { get; set; }
        public string? TSYEAR_INV_MESNO { get; set; }
        public string? TSYEAR_INV_ANM { get; set; }
        public string? TSYEAR_INV_DJGLOC { get; set; }
        public int? TTC_BARCODE_IDX { get; set; }
        public string? TTC_BARCODENM { get; set; }
        public int? TTC_ORDER_IDX { get; set; }
        public string? TTC_BC_WORK { get; set; }
        public int? TTC_BOM_IDX { get; set; }
        public int? TTC_PART_IDX { get; set; }
        public double? TTC_BOMSNP { get; set; }
        public string? TCC_DSVYN { get; set; }
        public int? TTC_PO_INX { get; set; }
        public int? TTC_PN_IDX { get; set; }
        public DateTime? TTC_PO_DT { get; set; }
        public int? TTC_PO { get; set; }
        public string? TTC_ENG { get; set; }
        public string? TC_PART_NM { get; set; }
        public string? TC_DESC { get; set; }
        public int? RAW_PART_IDX { get; set; }
        public int? TC_SIZE { get; set; }
        public string? TC_MC { get; set; }
        public int? TC_PACKUNIT { get; set; }
        public string? TC_LOC { get; set; }
        public double? TC_W_S { get; set; }
        public double? TC_W_MS { get; set; }
        public string? IN_USER { get; set; }
        public int? BNDLST_IDX { get; set; }
        public string? BNDLST_NM { get; set; }
        public double? BNDLST_MIN { get; set; }
        public double? BNDLST_MAX { get; set; }
        public double? STRENGTH { get; set; }
        public int? FORCE_IDX { get; set; }
        public string? FORCE_NM { get; set; }
        public double? FORCE_MIN { get; set; }
        public double? FORCE_MAX { get; set; }
        public int? FORCE_USW_IDX { get; set; }
        public string? FORCE_USW_NM { get; set; }
        public double? FORCE_USW_MIN_HORI { get; set; }
        public double? FORCE_USW_MIN_VERT { get; set; }
        public int? TOOL_HIS_IDX { get; set; }
        public DateTime? WORK_DTM { get; set; }
        public int? TOOL_IDX { get; set; }
        public int? WK_QTY { get; set; }
        public string? CONTENT { get; set; }
        public string? APPLICATOR { get; set; }
        public string? SEQ_TOT { get; set; }
        public int? TOO_SUPPLY { get; set; }
        public int? MAX_CNT { get; set; }
        public int? TOT_WK_CNT { get; set; }
        public int? WK_CNT { get; set; }
        public string? SPP_NO { get; set; }
        public string? TYPE { get; set; }
        public string? GAUGE { get; set; }
        public string? COPL_NOR { get; set; }
        public string? COPL_SPE { get; set; }
        public string? INSPL_SEALTYPE { get; set; }
        public string? INSPL_NONSEAL { get; set; }
        public string? INSPL_XTYPE { get; set; }
        public string? INSPL_KTYPE { get; set; }
        public string? INSPL_SPE { get; set; }
        public string? ANVIL_NOR { get; set; }
        public string? ANVIL_SPE { get; set; }
        public string? CMU_NOR { get; set; }
        public string? CMU_SPE { get; set; }
        public string? IMU_NOR { get; set; }
        public string? IMU_NONSEAL { get; set; }
        public string? IMU_SPE { get; set; }
        public string? CUTPL_ONE { get; set; }
        public string? CUTPL_DET { get; set; }
        public string? CUTAN_ONE { get; set; }
        public string? CUTAN_DET { get; set; }
        public string? CUTHO_ONE { get; set; }
        public string? CUTHO_DET { get; set; }
        public string? RRBLK_ONE { get; set; }
        public string? RRBLK_DET { get; set; }
        public string? RRCUTHO_ONE { get; set; }
        public string? RRCUTHO_DET { get; set; }
        public string? FRCUTHO_ONE { get; set; }
        public string? FRCUTHO_DET { get; set; }
        public string? RRCUTAN_ONE { get; set; }
        public string? RRCUTAN_DET { get; set; }
        public string? WRDN_ONE { get; set; }
        public string? WRDN_DET { get; set; }
        public string? COMB_CODE { get; set; }
        public int? TOOLMASTER_IDX { get; set; }
        public string? SEQ { get; set; }
        public int? TUSER_IDX { get; set; }
        public string? TS_MC_NM { get; set; }
        public DateTime? TS_DATE { get; set; }
        public DateTime? TS_TIME_ST { get; set; }
        public DateTime? TS_TIME_END { get; set; }
        public string? TS_USER { get; set; }
        public string? TS_USERID { get; set; }
        public string? TS_USER_IP { get; set; }
        public string? TS_USER_CNN { get; set; }
        public int? WORK_IDX { get; set; }
        public string? GROUP_CODE { get; set; }
        public string? W_GRC { get; set; }
        public int? W_PEP { get; set; }
        public int? GOOD_QTY { get; set; }
        public int? BAD_QTY { get; set; }
        public int? ETC_QTY { get; set; }
        public DateTime? WK_ST { get; set; }
        public DateTime? WK_ET { get; set; }
        public string? ROUTER { get; set; }
        public string? WORK_RMK { get; set; }
        public string? MC_NM { get; set; }
        public string? Q_CON { get; set; }
        public int? TOOLWORK_IDX { get; set; }
        public string? TOOL_WORK { get; set; }
        public int? TOT_WK_QTY { get; set; }
        int? WK_IDX { get; set; }
        public int? TORDER_IDX { get; set; }
        public string? MC_NO { get; set; }
        public string? WK_TERM { get; set; }
        public string? WK_CM { get; set; }
        public int? SETTING_IDX { get; set; }
        public string? SUB_NM { get; set; }
        public double? BASIC_TIME { get; set; }
        public string? UNIT { get; set; }
        public double? TIME { get; set; }
        public int? ZADMIN_FUNCTION_IDX { get; set; }
        public string? ZADMIN_FUNCTION_CODE { get; set; }
        public string? ZADMIN_FUNCTION_NAME { get; set; }
        public string? ZADMIN_FUNCTION_YN { get; set; }
        public string? ZADMIN_FUNCTION_DATE { get; set; }
        public string? ZADMIN_FUNCTION_REMARK { get; set; }
        public int? DELP_IDX { get; set; }
        public DateTime? DELP_DATE { get; set; }
        public string? DELP_DEPT { get; set; }
        public string? MES_MENU { get; set; }
        public string? DELP_NAME { get; set; }
        public string? DELP_DETIL { get; set; }
        public string? FILE_DSYN { get; set; }
        public string? FILE_NM { get; set; }
        public string? FILE_EX { get; set; }
        public double? FILE_SIZE { get; set; }
        public string? STATE { get; set; }
        public string? PROGRESS { get; set; }
        public DateTime? DONE_DATE { get; set; }
        public string? MES_VER { get; set; }
        public string? DELP_DELT { get; set; }
        public string? RESULT { get; set; }
        public string? DEP_PHOTO { get; set; }
        public int? IDX { get; set; }
        public string? MENU_NM { get; set; }
        public string? TAB_NAME { get; set; }
        public string? REV_NO { get; set; }
        public string? DN_YN { get; set; }
        public string? BUTTON_NM { get; set; }
        public string? PRG_CODE { get; set; }
        public string? DATA_TEXT { get; set; }
        public string? SQL_NM { get; set; }
        public int? VER_IDX { get; set; }
        public int? VER_MAJOR { get; set; }
        public int? VER_MINJOR { get; set; }
        public int? VER_BUILD { get; set; }
        public int? VER_REVISION { get; set; }
        public string? COMP_NM { get; set; }
        public double? SUM_COST { get; set; }
        public string? MIN_DT { get; set; } 
        public string? MAX_DT { get; set; }
        public int? NOT_WORK { get; set; } 
        public int? LEAD_RAT { get; set; } 
        public int? PO_SUM { get; set; } 
        public int? ACT_SUM { get; set; } 
        public int? ACT_RAT { get; set; }
        public string? ECNNo { get; set; }
        public string? ProductionLineName { get; set; }
        public string? ProcessName { get; set; }
        public string? LineName { get; set; }


        public string? LineType { get; set; }
      
        public string? Machine_Type { get; set; }
        public decimal? Total_Production { get; set; }
        public decimal? Avg_OperationRate { get; set; }
        public decimal? Avg_UPH { get; set; }
        public string? APPLICATOR_LOT { get; set; }
        public string? DeviceGroup { get; set; }
        public string? DeviceCode { get; set; }
        public string? ROW_NO { get; set; }
        public SuperResult()
        {
        }
    }
}

