namespace MESService.Model
{
    public partial class SuperResultTranfer : SuperResult
    {
        public string? Tube_Cutting_Part_No { get; set; }
        public string? ORDER_DATE { get; set; }
        public string? INDEX { get; set; }
        public string? LIST { get; set; }
        public string? CUT_ORDER { get; set; }
        public string? SNP { get; set; }
        public string? po_result { get; set; }
        public bool? DGV_result3 { get; set; }
        public string? ORDER_QTY { get; set; }
        public string? COLN_PARTNM { get; set; }
        public string? COLN_SHIONO { get; set; }
        public string? COLN_LOC { get; set; }
        public string? DGV_ARESULT { get; set; }
        public string? COLN_PARTNO { get; set; }
        public string? Coln1 { get; set; }
        public string? Coln2 { get; set; }
        public string? Coln3 { get; set; }
        public string? Coln4 { get; set; }
        public string? Coln5 { get; set; }
        public string? Coln6 { get; set; }
        public string? Coln7 { get; set; }
        public string? DGV_BARID { get; set; }
        public int? MAX_SNP { get; set; }
        public bool? CHK { get; set; }
        public int? CODE { get; set; }
        public int? REWORK_QTY { get; set; }
        public string? PART_NAME { get; set; }
        public string? BOM_GROUP { get; set; }
        public string? MODEL { get; set; }
        public string? PART_FamilyPC { get; set; }
        public string? Packing_Unit { get; set; }
        public string? Item_TypeK { get; set; }
        public string? Item_TypeE { get; set; }
        public string? Location { get; set; }
        public string? PART_USE { get; set; }
        public DateTime? Creation_date { get; set; }
        public string? Creation_User { get; set; }
        public DateTime? Update_Date { get; set; }
        public double? STOCK { get; set; }       
        public string? Pallet_NO { get; set; }
        public string? Shipping_NO { get; set; }
        public string? Receipt_Data { get; set; }
        public string? Receipt_USER { get; set; }
        public string? Release_Date { get; set; }
        public string? Release_USER { get; set; }
        public string? BR_DSCN { get; set; }
        public string? LOC { get; set; }
        public string? OR_DT { get; set; }

        public string? NO { get; set; }
        public string? DateRDCE { get; set; }
        public string? SUM_QTY { get; set; }
        public string? STOCK_QTY { get; set; }
        public string? USER { get; set; }
        public string? MT_EXCEL { get; set; }
        public string? YEAR { get; set; }
        public string? MONTH { get; set; }
        public string? WEEK { get; set; }
        public string? P_COUNT { get; set; }
        public string? BC_COUNT { get; set; }
        public string? OUT_QTY { get; set; }
        public string? PO_PLAN { get; set; }
        public string? STAY_QTY { get; set; }
        public string? STAY_RATIO { get; set; }
        public string? BC_DSCN_YN { get; set; }
        public string? MAX_PKG { get; set; }

        public bool? dgvcheck { get; set; }
        public string? PARTNO { get; set; }
        public string? GOODS { get; set; }
        public string? QUANTITY { get; set; }
        public string? NWEIGHT { get; set; }
        public string? GWEIGHT { get; set; }
        public string? PalletNo { get; set; }
        public string? ShippedNo { get; set; }
        public string? inputdate { get; set; }
        public string? Barcode { get; set; }
        public int? ParentID { get; set; }
        public int? WireNumber { get; set; }
        public bool? Visible { get; set; }
        public double? PriceTerm1 { get; set; }
        public double? SealPrice1 { get; set; }
        public double? WirePrice { get; set; }
        public double? PriceTerm2 { get; set; }
        public double? SealPrice2 { get; set; }
        public DateTime? DAY { get; set; }
        public string? FVWR { get; set; }
        public string? ADDFILE { get; set; }
        public string? WireCode { get; set; }

        public string? Machine { get; set; }
        public string? Size { get; set; }
        public string? Raw_Material_Part { get; set; }
        public string? Description { get; set; }
        public string? LOAD { get; set; }
        public string? DATEString { get; set; }
        public string? FG_PART_NO { get; set; }
        public string? FG_PART_NAME { get; set; }
        public string? FG_PART_MODEL { get; set; }
        public string? TCC_PARTNO { get; set; }
        public string? IN_USERNAME { get; set; }
        public string? OUT_USERNAME { get; set; }
        public string? Meter { get; set; }
        public decimal? MIN { get; set; }
        public decimal? MT { get; set; }
        public string? ORDER { get; set; }
        public string? STAGE { get; set; }
        public string? DJG_CODE { get; set; }
        public string? SHEET_NO { get; set; }
        public int? BOX_COUNT { get; set; }
        public string? DSCN { get; set; }
        public string? FAMILY { get; set; }
        public string? BOX { get; set; }
        public string? Change_QTY { get; set; }
        public string? Incoming_QTY { get; set; }
        public string? Difference_QTY { get; set; }
        public string? MES_STOCK { get; set; }
        public string? EXCEL { get; set; }
        public string? Verification { get; set; }
        public string? PW1 { get; set; }
        public string? PW2 { get; set; }
        public string? PW3 { get; set; }
        public string? PW4 { get; set; }
        public string? PW5 { get; set; }
        public string? PW6 { get; set; }
        public string? P_SUM { get; set; }
        public string? DATE_STOCK { get; set; }
        public string? NOW_QTY { get; set; }
        public string? SHIP_SUM { get; set; }
        public string? W1 { get; set; }
        public string? W2 { get; set; }
        public string? W3 { get; set; }
        public string? W4 { get; set; }
        public string? W5 { get; set; }
        public string? W6 { get; set; }
        public string? D00 { get; set; }
        public string? D01 { get; set; }
        public string? D02 { get; set; }
        public string? D03 { get; set; }
        public string? D04 { get; set; }
        public string? D05 { get; set; }
        public string? D06 { get; set; }
        public string? D07 { get; set; }
        public string? D08 { get; set; }
        public string? D09 { get; set; }
        public string? D10 { get; set; }
        public string? D11 { get; set; }
        public string? D12 { get; set; }
        public string? D13 { get; set; }
        public string? D14 { get; set; }
        public string? D15 { get; set; }
        public string? D16 { get; set; }
        public string? D17 { get; set; }
        public string? D18 { get; set; }
        public string? D19 { get; set; }
        public string? D20 { get; set; }
        public string? D21 { get; set; }
        public string? D22 { get; set; }
        public string? D23 { get; set; }
        public string? D24 { get; set; }
        public string? D25 { get; set; }
        public string? D26 { get; set; }
        public string? D27 { get; set; }
        public string? D28 { get; set; }
        public string? D29 { get; set; }
        public string? D30 { get; set; }
        public string? D31 { get; set; }
        public string? UNIT_V { get; set; }
        public string? UNIT_VN { get; set; }
        public string? UNIT_KR { get; set; }
        public string? UNIT_EN { get; set; }
        public string? UNIT_K { get; set; }
        public string? COST { get; set; }
        public string? Company { get; set; }
        public decimal? NON_WORK_TIME { get; set; }
        public decimal? WORKG_TIME { get; set; }
        public decimal? WG_RUS { get; set; }
        public decimal? WORK_TIME { get; set; }
        public decimal? WG_RUS2 { get; set; }
        public decimal? WIRE_L { get; set; }
        public decimal? RUS { get; set; }
        public decimal? ACT_QTY { get; set; }
        public string? RAW_PART_NO { get; set; }
        public string? S_USER { get; set; }
        public string? MC_NAME { get; set; }
        public string? R14 { get; set; }
        public decimal? Ajust_CNT { get; set; }
        public decimal? LCount { get; set; }
        public decimal? RAT { get; set; }
        public string? PART_CODE { get; set; }
        public decimal? Raw_Material { get; set; }
        public decimal? Finish_Goods { get; set; }
        public decimal? WIP { get; set; }
        public decimal? SUM { get; set; }
        public string? GROUP { get; set; }

        public decimal? MAX_COUNT { get; set; }
        public decimal? TOTAL_COUNT { get; set; }
        public decimal? WORK_COUNT { get; set; }
        public decimal? FREE_COUNT { get; set; }
        public decimal? OVER_COUNT { get; set; }
        public double? A501 { get; set; }
        public double? A502 { get; set; }
        public double? A801 { get; set; }
        public double? A802 { get; set; }
        public double? A803 { get; set; }
        public double? A804 { get; set; }
        public double? A805 { get; set; }
        public double? A806 { get; set; }
        public double? A807 { get; set; }
        public double? A808 { get; set; }
        public double? A809 { get; set; }
        public double? A810 { get; set; }
        public double? A811 { get; set; }
        public double? A812 { get; set; }
        public double? A813 { get; set; }
        public double? A814 { get; set; }
        public double? A815 { get; set; }
        public double? A816 { get; set; }
        public double? A830 { get; set; }
        public double? A831 { get; set; }
        public double? A832 { get; set; }
        public double? A833 { get; set; }
        public double? TIME_M { get; set; }
        public double? TIME_S { get; set; }
        public string? CODEH02 { get; set; }
        public string? TIMEH02 { get; set; }
        public string? E_USER { get; set; }
        public string? CreateBy { get; set; }
        public string? CreateTime { get; set; }
        public string? UpdateBy { get; set; }
        public string? UpdateTime { get; set; }
        public int? COUNT { get; set; }
        public int? INPUT_DATA { get; set; }
        public string? ADD_1 { get; set; }
        public string? ADD_2 { get; set; }
        public string? ADD_3 { get; set; }
        public string? ADD_4 { get; set; }
        public string? ADD_5 { get; set; }
        public string? ADD_6 { get; set; }
        public string? OVER_9 { get; set; }
        public string? OVER_10 { get; set; }
        public string? TNM { get; set; }
        public string? DJG_LOC { get; set; }
        public int? MES_NO { get; set; }
        public string? MES_ORDER { get; set; }
        public string? USED_STOCK { get; set; }
        public int? SUM_TIME { get; set; } 
        public string? W_PN { get; set; }
        public string? T1_PN { get; set; }
        public string? S1_PN { get; set; }
        public string? T2_PN { get; set; }
        public string? S2_PN { get; set; }
        public string? PART_GRP { get; set; }
        public int? NEXT_PO { get; set; }
        public int? BOX_QTY { get; set; }
        public string? Inventory { get; set; }
        public string? PO_status { get; set; }       
        public string? CNF { get; set; }
        public int? CONT { get; set; }
        public int? QTY1 { get; set; }
        public int? DGV1_QTY { get; set; }
        public int? DGV1_BOXC { get; set; }
        public string? DGV1_PARTNO { get; set; }
        public string? PART_LINE { get; set; }
        public int? Not_yet_packing { get; set; }
        public string? PLET_NO1 { get; set; }
        public string? PALLET_SERIAL_NO { get; set; }
        public string? PART_STAGE { get; set; }
        public DateTime? SHIPPING_DATE { get; set; }
        public DateTime? INPUT_DATE { get; set; }
        public string? PALLET_CODE { get; set; }
        public string? SERIAL_ID { get; set; }
        public string? Good_BRCODE { get; set; }
        public string? Ship_Status { get; set; }
        public string? PLT { get; set; }
        public string? Serial_Barcode { get; set; }
        public string? PO_IDX { get; set; }
        public string? Split { get; set; }
        public string? ASSY_NO { get; set; }
        public string? SAFETY_QTY { get; set; }
        public string? TOTAL_QTY { get; set; }
        public double? QTY_REM { get; set; }
        public string? ASSET_NAME { get; set; }
        public string? ASSET_ID { get; set; }
        public string? PURCHASE_DATE { get; set; }
        public string? USE_DATE { get; set; }
        public string? SPECIFICATION { get; set; }
        public string? DEPARTMENT { get; set; }
        public string? USER_NAME { get; set; }
        public string? STATUS { get; set; }
        public int? QTY_STOCK { get; set; }
        public string? LEAD_NO1 { get; set; }
        public string? Stay { get; set; }
        public string? Working { get; set; }
        public string? Complete { get; set; }
        public string? Close { get; set; }
        public string? DEP_CODE { get; set; }
        public double? RUN_RAT { get; set; }
        public decimal? UPH { get; set; }
        public string? Hour { get; set; }
        public double? ZA801 { get; set; }
        public double? ZA802 { get; set; }
        public double? ZA803 { get; set; }
        public double? ZA804 { get; set; }
        public double? ZA805 { get; set; }
        public double? ZA806 { get; set; }
        public double? ZA807 { get; set; }
        public double? ZA808 { get; set; }
        public double? ZA809 { get; set; }
        public double? ZA810 { get; set; }


        public string? SHIP_NO { get; set; }
        public int? COL1 { get; set; }
        public int? COL2 { get; set; }
        public int? COL3 { get; set; }
        public int? COL4 { get; set; }
        public DateTime? FIRST_TIME { get; set; }
        public DateTime? END_TIME { get; set; }
        public string? TERM { get; set; }
      //  public string? WK_TERM { get; set; }
        public int? WORK_QTY { get; set; }
        public string? BARCODE_NAME { get; set; }
        public string? ORDER_NO { get; set; }
        public int? T1_W_QTY { get; set; }
        public int? T2_W_QTY { get; set; }
        public string? Stock_status { get; set; }
        public int? CHK_QTY { get; set; }
        public DateTime? IN_DATE { get; set; }
        public DateTime? OUT_DATE { get; set; }
        public int? T1_CONT { get; set; }
        public int? TOOL_MAX1 { get; set; }
        public int? T2_CONT { get; set; }
        public int? TOOL_MAX2 { get; set; }
        public string? LH { get; set; }
        public string? RH { get; set; }
        public string? T1_PARTNO { get; set; }
        public string? T2_PARTNO { get; set; }
        public string? Work { get; set; }
        public int? TOT_COUNT { get; set; }
        public int? QtyPlan { get; set; }
        public int? QtyActual { get; set; }
        public DateTime? DatePlan { get; set; }
        public string? MCPlan { get; set; }
        public string? TestTime { get; set; }
        public string? FullName { get; set; }
        public string? HOOK { get; set; }
        public string? T1 { get; set; }
        public string? T2 { get; set; }
        public string? S1 { get; set; }
        public string? S2 { get; set; }
        public string? REM_QTY { get; set; }
        public string? ACT { get; set; }
        public string? LS_DATE { get; set; }
        public DateTime? DATEMIN { get; set; }
        public DateTime? DATEMAX { get; set; }
        public string? ORDER_ST { get; set; }
        public string? DVC { get; set; }
        public string? CM_PALLET_NO { get; set; }
        public double? W_Length1 { get; set; }
        public string? MENU_NM_VIE { get; set; }
        public string? TestPos { get; set; }
        public double? WIRE_FORCEStandard { get; set; }
        public double? WIRE_FORCEFirst { get; set; }
        public double? WIRE_FORCEMid { get; set; }
        public double? WIRE_FORCEEnd { get; set; }
        public double? LengthStandard { get; set; }
        public int? LengthFirst { get; set; }
        public int? LengthMid { get; set; }
        public int? LengthEnd { get; set; }
        public string? CCH1Standard { get; set; }
        public string? CCH1Firt { get; set; }
        public string? CCH1Mid { get; set; }
        public string? CCH1End { get; set; }
        public string? CCW1Standard { get; set; }
        public string? CCW1Firt { get; set; }
        public string? CCW1Mid { get; set; }
        public string? CCW1End { get; set; }
        public string? CCH2Standard { get; set; }
        public string? CCH2Firt { get; set; }
        public string? CCH2Mid { get; set; }
        public string? CCH2End { get; set; }
        public string? CCW2Standard { get; set; }
        public string? CCW2Firt { get; set; }
        public string? CCW2Mid { get; set; }
        public string? CCW2End { get; set; }
        public string? WIRE_PARTNO { get; set; }
        public string? S1_PARTNO { get; set; }
        public string? S2_PARTNO { get; set; }
        public string? APP { get; set; }
        public string? APP_NAME { get; set; }
        public int? MAX { get; set; }
        public string? T1_NM { get; set; }
        public string? T2_NM { get; set; }
        public string? M_NAME { get; set; }
        public string? M_W_Length { get; set; }
        public string? S_NAME { get; set; }
        public string? S_W_Length { get; set; }
        public int? S_SUM { get; set; }
        public string? E_CHK { get; set; }
        public int? B_SIZE { get; set; }
        public int? T1_IDX { get; set; }
        public int? S1_IDX { get; set; }
        public int? T2_IDX { get; set; }
        public int? S2_IDX { get; set; }
        public int? WIRE_IDX { get; set; }
        public int? T1_QTY { get; set; }
        public int? T2_QTY { get; set; }
        public int? S1_QTY { get; set; }
        public int? S2_QTY { get; set; }
        public string? T1_ORDER { get; set; }
        public string? T1_COMP { get; set; }
        public string? T2_ORDER { get; set; }
        public string? T2_COMP { get; set; }
        public string? S1_ORDER { get; set; }
        public string? S1_COMP { get; set; }
        public string? S2_ORDER { get; set; }
        public string? S2_COMP { get; set; }
        public string? WR_ORDER { get; set; }
        public string? WR_COMP { get; set; }
        public string? DC_YN { get; set; }
        public int? ReasonID { get; set; }
        public string? Reason { get; set; }
        public string? PART_SNP1 { get; set; }
        public double? QuantityActual { get; set; }
        public double? QuantityGAP { get; set; }
        public int? T1_TOO_IDX { get; set; }
        public int? B218 { get; set; }
        public int? B219 { get; set; }
        public int? B220 { get; set; }
        public int? B221 { get; set; }
        public string? M_PART { get; set; }
        public string? S_PART { get; set; }
        public int? DURATION { get; set; }
        public long LineListID { get;  set; }
        public string LineGroup { get;  set; }
        public string ECN { get;  set; }
        public bool? GP12 { get;  set; }
        public string LineFamily { get;  set; }
        public long NGListID { get;  set; }
        public string ErrorCode { get;  set; }
        public string Picture { get;  set; }
        public long NGList_ID { get; set; }
        public string TrolleyCode { get; set; }
        public SuperResultTranfer()
        {
        }
    }
}

