export const environment = {
  production: true,
  APIURL: "http://api.dongjin-global.com:88/api/v1/",
  APIRootURL: "http://api.dongjin-global.com:88/",
  APIInvoiceURL: "http://api.dongjin-global.com:88/api/v1/",
  APIInvoiceRootURL: "http://api.dongjin-global.com:88/",
  APIMasterDataURL: "http://api.dongjin-global.com:88/api/v1/",
  APIMasterDataRootURL: "http://api.dongjin-global.com:88/",
  APIMaterialURL: "http://api.dongjin-global.com:88/api/v1/",
  APIMaterialRootURL: "http://api.dongjin-global.com:88/",
  APIMembershipURL: "http://api.dongjin-global.com:88/api/v1/",
  APIMembershipRootURL: "http://api.dongjin-global.com:88/",
  APIProductionOrderURL: "http://api.dongjin-global.com:88/api/v1/",
  APIProductionOrderRootURL: "http://api.dongjin-global.com:88/",
  APIReportURL: "http://api.dongjin-global.com:88/api/v1/",
  APIReportRootURL: "http://api.dongjin-global.com:88/",
  APIWarehouseURL: "http://api.dongjin-global.com:88/api/v1/",
  APIWarehouseRootURL: "http://api.dongjin-global.com:88/",
  APIWarehouseInputURL: "http://api.dongjin-global.com:88/api/v1/",
  APIWarehouseInputRootURL: "http://api.dongjin-global.com:88/",
  APIWarehouseInputDetailURL: "http://api.dongjin-global.com:88/api/v1/",
  APIWarehouseInputDetailRootURL: "http://api.dongjin-global.com:88/",
  APIWarehouseInputDetailBarcodeURL: "http://api.dongjin-global.com:88/api/v1/",
  APIWarehouseInputDetailBarcodeRootURL: "http://api.dongjin-global.com:88/",
  APIWarehouseInputDetailBarcode02URL: "http://api.dongjin-global.com:88/api/v1/",
  APIWarehouseInputDetailBarcode02RootURL: "http://api.dongjin-global.com:88/",
  APIWarehouseOutputURL: "http://api.dongjin-global.com:88/api/v1/",
  APIWarehouseOutputRootURL: "http://api.dongjin-global.com:88/",
  APIWarehouseOutputDetailURL: "http://api.dongjin-global.com:88/api/v1/",
  APIWarehouseOutputDetailRootURL: "http://api.dongjin-global.com:88/",
  APIWarehouseOutputDetailBarcodeURL: "http://api.dongjin-global.com:88/api/v1/",
  APIWarehouseOutputDetailBarcodeRootURL: "http://api.dongjin-global.com:88/",
  APIWarehouseOutputDetailBarcode02URL: "http://api.dongjin-global.com:88/api/v1/",
  APIWarehouseOutputDetailBarcode02RootURL: "http://api.dongjin-global.com:88/",
  APIMESURL: "http://api.dongjin-global.com:88/api/v2/",
  APIMESRootURL: "http://api.dongjin-global.com:88/",
  PrintURL: "http://127.0.0.1/api/v1/",
  PrintRootURL: "http://127.0.0.1/",
  LoadingFile: "loading.gif",
  DialogConfigWidth: "80%",
  InitializationString: "",
  InitializationNumber: 0,
  Token: "Token",
  Homepage: "Homepage",
  Login: "Login",
  Bearer: "Bearer null",
  UploadSuccess: "Upload success",
  UploadNotSuccess: "Upload not success",
  SaveSuccess: "Save success",
  SaveNotSuccess: "Save not success",
  DeleteConfirm: "Do you want to delete this data?",
  DeleteSuccess: "Delete success.",
  DeleteNotSuccess: "Delete not success",
  DataExists: "Data already exists",
  LoginNotSuccess: "Login not success",
  UserNameNotExists: "Account does not exist",
  UserNameExists: "Account already exists",
  UserNameRequired: "Account is required.",
  IsPasswordValidWithRegex: "Password must be greater than 08 characters, including Uppercase, Numbers, Special characters (@,#,$,%...)",
  Help: "This function is not available for Web applications.",
  PageTitle: "DONGJIN GLOBAL COMPANY LIMITED",
  PageTitleShort: "DONGJIN",
  PageDescription: "DONGJIN GLOBAL COMPANY LIMITED | MES",
  ScanSuccess: "FIFO Correct",
  ScanNotSuccess: "FIFO Not Correct",
  Synchronizing: "The system is synchronizing",

  IPRegistryIP: "IPRegistryIP",
  IPRegistryIPLocal: "IPRegistryIPLocal",
  IPRegistryDevice: "IPRegistryDevice",
  IPRegistryLongitude: "IPRegistryLongitude",
  IPRegistryLatitude: "IPRegistryIPLatitude",
  IPRegistryCountryName: "IPRegistryCountryName",
  IPRegistryRegionName: "IPRegistryRegionName",
  IPRegistryCityName: "IPRegistryCityName",
  IPRegistryURL: "https://api.ipregistry.co/?key=tryout",

  Logo312_80: "/image/logo312_80.png",

  UserID: "UserID",
  MembershipID: "MembershipID",
  UserName: "UserName",
  FullName: "FullName",
  FileName: "FileName",
  CompanyID: "CompanyID",
  CategoryDepartmentID: "CategoryDepartmentID",
  LanguageID: "LanguageID",

  MapZoom: 18.5,
  Latitude: 10.5125269,
  Longitude: 107.3041063,
  MaptilerAPIKey: "6iFTqps4QVACLERa26MA",

  Timer: 300000,
  TimerMax: 30000,
  PageSize: 20,
  PageSizeMax: 1000000,
  CompanyIDDJG: 16,
  DepartmentID: 23,
  CategoryPositionID: 12,
  CategoryMaterialID: 9,
  CategoryCompanyID: 11,
};
