import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { MatTableDataSource } from '@angular/material/table';
import { environment } from 'src/environments/environment';
import { ProductionOrderDetail } from './ProductionOrderDetail.model';
import { BaseService } from './Base.service';
import { BaseResult } from 'src/app/shared/ERP/BaseResult.model';

@Injectable({
    providedIn: 'root'
})
export class ProductionOrderDetailService extends BaseService {
    DisplayColumns001: string[] = ['No', 'ID', 'ParentID', 'ParentName', 'CreateDate', 'CreateUserID', 'CreateUserCode', 'CreateUserName', 'UpdateDate', 'UpdateUserID', 'UpdateUserCode', 'UpdateUserName', 'RowVersion', 'SortOrder', 'Active', 'Code', 'Name', 'Display', 'Description', 'Note', 'FileName', 'CompanyID', 'CompanyName', 'MaterialID', 'MaterialCode', 'MaterialName', 'MaterialPartNumber', 'CategoryUnitID', 'CategoryUnitName', 'CategoryFamilyID', 'CategoryFamilyName', 'QuantitySNP', 'QuantityBox', 'Quantity00', 'QuantityActual00', 'QuantityGAP00', 'Date01', 'Date01Name', 'CategoryVehicleID01', 'CategoryVehicleName01', 'Quantity01', 'QuantityActual01', 'QuantityGAP01', 'Date02', 'Date02Name', 'CategoryVehicleID02', 'CategoryVehicleName02', 'Quantity02', 'QuantityActual02', 'QuantityGAP02', 'Date03', 'Date03Name', 'CategoryVehicleID03', 'CategoryVehicleName03', 'Quantity03', 'QuantityActual03', 'QuantityGAP03', 'Date04', 'Date04Name', 'CategoryVehicleID04', 'CategoryVehicleName04', 'Quantity04', 'QuantityActual04', 'QuantityGAP04', 'Date05', 'Date05Name', 'CategoryVehicleID05', 'CategoryVehicleName05', 'Quantity05', 'QuantityActual05', 'QuantityGAP05', 'Date06', 'Date06Name', 'CategoryVehicleID06', 'CategoryVehicleName06', 'Quantity06', 'QuantityActual06', 'QuantityGAP06', 'Date07', 'Date07Name', 'CategoryVehicleID07', 'CategoryVehicleName07', 'Quantity07', 'QuantityActual07', 'QuantityGAP07', 'Date08', 'Date08Name', 'CategoryVehicleID08', 'CategoryVehicleName08', 'Quantity08', 'QuantityActual08', 'QuantityGAP08', 'Date09', 'Date09Name', 'CategoryVehicleID09', 'CategoryVehicleName09', 'Quantity09', 'QuantityActual09', 'QuantityGAP09', 'Date10', 'Date10Name', 'CategoryVehicleID10', 'CategoryVehicleName10', 'Quantity10', 'QuantityActual10', 'QuantityGAP10', 'Date11', 'Date11Name', 'CategoryVehicleID11', 'CategoryVehicleName11', 'Quantity11', 'QuantityActual11', 'QuantityGAP11', 'Date12', 'Date12Name', 'CategoryVehicleID12', 'CategoryVehicleName12', 'Quantity12', 'QuantityActual12', 'QuantityGAP12', 'Date13', 'Date13Name', 'CategoryVehicleID13', 'CategoryVehicleName13', 'Quantity13', 'QuantityActual13', 'QuantityGAP13', 'Date14', 'Date14Name', 'CategoryVehicleID14', 'CategoryVehicleName14', 'Quantity14', 'QuantityActual14', 'QuantityGAP14', 'Date15', 'Date15Name', 'CategoryVehicleID15', 'CategoryVehicleName15', 'Quantity15', 'QuantityActual15', 'QuantityGAP15', 'Save'];
    DisplayColumns002: string[] = ['No', 'ID', 'CategoryFamilyName', 'MaterialName', 'CategoryUnitName', 'QuantitySNP', 'QuantityBox', 'Priority', 'Quantity00', 'QuantityActual00', 'QuantityGAP00', 'Date01', 'QuantityActual01', 'QuantityGAP01', 'Date02', 'QuantityActual02', 'QuantityGAP02', 'Date03', 'QuantityActual03', 'QuantityGAP03', 'Date04', 'QuantityActual04', 'QuantityGAP04', 'Date05', 'QuantityActual05', 'QuantityGAP05', 'Date06', 'QuantityActual06', 'QuantityGAP06', 'Date07', 'QuantityActual07', 'QuantityGAP07', 'Date08', 'QuantityActual08', 'QuantityGAP08', 'Date09', 'QuantityActual09', 'QuantityGAP09', 'Date10', 'QuantityActual10', 'QuantityGAP10', 'Date11', 'QuantityActual11', 'QuantityGAP11', 'Date12', 'QuantityActual12', 'QuantityGAP12', 'Date13', 'QuantityActual13', 'QuantityGAP13', 'Date14', 'QuantityActual14', 'QuantityGAP14', 'Date15', 'QuantityActual15', 'QuantityGAP15'];
    DisplayColumns003: string[] = ['No', 'ID', 'Code', 'CategoryFamilyName', 'MaterialName', 'CategoryUnitName', 'QuantitySNP', 'QuantityBox', 'Priority', 'Quantity00', 'QuantityActual00', 'QuantityGAP00', 'Date01', 'QuantityActual01', 'QuantityGAP01', 'Date02', 'QuantityActual02', 'QuantityGAP02', 'Date03', 'QuantityActual03', 'QuantityGAP03', 'Date04', 'QuantityActual04', 'QuantityGAP04', 'Date05', 'QuantityActual05', 'QuantityGAP05', 'Date06', 'QuantityActual06', 'QuantityGAP06', 'Date07', 'QuantityActual07', 'QuantityGAP07', 'Date08', 'QuantityActual08', 'QuantityGAP08', 'Date09', 'QuantityActual09', 'QuantityGAP09', 'Date10', 'QuantityActual10', 'QuantityGAP10', 'Date11', 'QuantityActual11', 'QuantityGAP11', 'Date12', 'QuantityActual12', 'QuantityGAP12', 'Date13', 'QuantityActual13', 'QuantityGAP13', 'Date14', 'QuantityActual14', 'QuantityGAP14', 'Date15', 'QuantityActual15', 'QuantityGAP15'];
    DisplayColumns004: string[] = ['No', 'ID', 'CategoryFamilyName', 'MaterialName', 'CategoryUnitName', 'QuantitySNP', 'BOMECN', 'Priority', 'Quantity00', 'QuantityActual00', 'QuantityGAP00', 'Date01', 'QuantityActual01', 'QuantityGAP01', 'Date02', 'QuantityActual02', 'QuantityGAP02', 'Date03', 'QuantityActual03', 'QuantityGAP03', 'Date04', 'QuantityActual04', 'QuantityGAP04', 'Date05', 'QuantityActual05', 'QuantityGAP05', 'Date06', 'QuantityActual06', 'QuantityGAP06', 'Date07', 'QuantityActual07', 'QuantityGAP07', 'Date08', 'QuantityActual08', 'QuantityGAP08', 'Date09', 'QuantityActual09', 'QuantityGAP09', 'Date10', 'QuantityActual10', 'QuantityGAP10', 'Date11', 'QuantityActual11', 'QuantityGAP11', 'Date12', 'QuantityActual12', 'QuantityGAP12', 'Date13', 'QuantityActual13', 'QuantityGAP13', 'Date14', 'QuantityActual14', 'QuantityGAP14', 'Date15', 'QuantityActual15', 'QuantityGAP15'];
    DisplayColumns005: string[] = ['No', 'ID', 'CategoryFamilyName', 'MaterialName', 'CategoryUnitName', 'QuantitySNP', 'BOMECN', 'BOMECNVersion', 'Priority', 'Quantity00', 'QuantityActual00', 'QuantityGAP00', 'Date01', 'QuantityActual01', 'QuantityGAP01', 'Date02', 'QuantityActual02', 'QuantityGAP02', 'Date03', 'QuantityActual03', 'QuantityGAP03', 'Date04', 'QuantityActual04', 'QuantityGAP04', 'Date05', 'QuantityActual05', 'QuantityGAP05', 'Date06', 'QuantityActual06', 'QuantityGAP06', 'Date07', 'QuantityActual07', 'QuantityGAP07', 'Date08', 'QuantityActual08', 'QuantityGAP08', 'Date09', 'QuantityActual09', 'QuantityGAP09', 'Date10', 'QuantityActual10', 'QuantityGAP10', 'Date11', 'QuantityActual11', 'QuantityGAP11', 'Date12', 'QuantityActual12', 'QuantityGAP12', 'Date13', 'QuantityActual13', 'QuantityGAP13', 'Date14', 'QuantityActual14', 'QuantityGAP14', 'Date15', 'QuantityActual15', 'QuantityGAP15'];
    DisplayColumns006: string[] = ['Save', 'No', 'ID', 'CategoryFamilyName', 'MaterialName', 'CategoryUnitName', 'QuantitySNP', 'BOMECN', 'BOMECNVersion', 'Priority', 'Quantity00', 'QuantityActual00', 'QuantityGAP00', 'Date01', 'QuantityActual01', 'QuantityGAP01', 'Date02', 'QuantityActual02', 'QuantityGAP02', 'Date03', 'QuantityActual03', 'QuantityGAP03', 'Date04', 'QuantityActual04', 'QuantityGAP04', 'Date05', 'QuantityActual05', 'QuantityGAP05', 'Date06', 'QuantityActual06', 'QuantityGAP06', 'Date07', 'QuantityActual07', 'QuantityGAP07', 'Date08', 'QuantityActual08', 'QuantityGAP08', 'Date09', 'QuantityActual09', 'QuantityGAP09', 'Date10', 'QuantityActual10', 'QuantityGAP10', 'Date11', 'QuantityActual11', 'QuantityGAP11', 'Date12', 'QuantityActual12', 'QuantityGAP12', 'Date13', 'QuantityActual13', 'QuantityGAP13', 'Date14', 'QuantityActual14', 'QuantityGAP14', 'Date15', 'QuantityActual15', 'QuantityGAP15'];
    DisplayColumns007: string[] = ['Save', 'No', 'ID', 'CategoryFamilyName', 'CategoryUnitName', 'QuantitySNP', 'BOMECN', 'BOMECNVersion', 'Priority', 'Quantity00', 'QuantityActual00', 'QuantityGAP00', 'Date01', 'QuantityActual01', 'QuantityGAP01', 'Date02', 'QuantityActual02', 'QuantityGAP02', 'Date03', 'QuantityActual03', 'QuantityGAP03', 'Date04', 'QuantityActual04', 'QuantityGAP04', 'Date05', 'QuantityActual05', 'QuantityGAP05', 'Date06', 'QuantityActual06', 'QuantityGAP06', 'Date07', 'QuantityActual07', 'QuantityGAP07', 'Date08', 'QuantityActual08', 'QuantityGAP08', 'Date09', 'QuantityActual09', 'QuantityGAP09', 'Date10', 'QuantityActual10', 'QuantityGAP10', 'Date11', 'QuantityActual11', 'QuantityGAP11', 'Date12', 'QuantityActual12', 'QuantityGAP12', 'Date13', 'QuantityActual13', 'QuantityGAP13', 'Date14', 'QuantityActual14', 'QuantityGAP14', 'Date15', 'QuantityActual15', 'QuantityGAP15'];
    DisplayColumns008: string[] = ['Save', 'Active', 'No', 'ID', 'CategoryFamilyName', 'CategoryUnitName', 'QuantitySNP', 'BOMECN', 'BOMECNVersion', 'Priority', 'Quantity00', 'QuantityActual00', 'QuantityGAP00', 'Date01', 'QuantityActual01', 'QuantityGAP01', 'Date02', 'QuantityActual02', 'QuantityGAP02', 'Date03', 'QuantityActual03', 'QuantityGAP03', 'Date04', 'QuantityActual04', 'QuantityGAP04', 'Date05', 'QuantityActual05', 'QuantityGAP05', 'Date06', 'QuantityActual06', 'QuantityGAP06', 'Date07', 'QuantityActual07', 'QuantityGAP07', 'Date08', 'QuantityActual08', 'QuantityGAP08', 'Date09', 'QuantityActual09', 'QuantityGAP09', 'Date10', 'QuantityActual10', 'QuantityGAP10', 'Date11', 'QuantityActual11', 'QuantityGAP11', 'Date12', 'QuantityActual12', 'QuantityGAP12', 'Date13', 'QuantityActual13', 'QuantityGAP13', 'Date14', 'QuantityActual14', 'QuantityGAP14', 'Date15', 'QuantityActual15', 'QuantityGAP15'];

    List: ProductionOrderDetail[] | undefined;
    ListFilter: ProductionOrderDetail[] | undefined;
    FormData!: ProductionOrderDetail;
    APIURL: string = environment.APIProductionOrderURL;
    APIRootURL: string = environment.APIProductionOrderRootURL;
    constructor(public httpClient: HttpClient) {
        super(httpClient);
        this.Controller = "ProductionOrderDetail";
    }
    GetByParentIDAndSearchStringToListAsync() {
        let url = this.APIURL + this.Controller + '/GetByParentIDAndSearchStringToListAsync';
        const formUpload: FormData = new FormData();
        formUpload.append('BaseParameter', JSON.stringify(this.BaseParameter));
        return this.httpClient.post(url, formUpload, { headers: this.Headers });
    }
}

